Repository mitodl/mitxonline, pull requests merged in 2021-08, with the labels that each got.

#41 Implement basic site footer content
  main/templates/footer.html
  static/images/mit.png
  static/scss/footer.scss
  static/scss/layout.scss
  static/scss/variables.scss
Labels: Waiting on Author

#36 Implement resource pages and links from site footer
  cms/api.py
  cms/api_test.py
  cms/blocks.py
  cms/factories.py
  cms/management/commands/configure_wagtail.py
  cms/migrations/0003_resourcepage.py
  cms/models.py
  cms/models_test.py
  cms/templates/resource_page.html
Labels: Waiting on Author

#44 Fix: forgot password regex failure fix and error message display
  authentication/views.py
  mail/api.py
  mail/api_test.py
  mail/exceptions.py
  main/urls.py
  main/views.py
  static/js/containers/pages/login/LoginForgotPasswordPage.js
  static/scss/auth.scss
Labels: Waiting on Author

#48 add header hero section details
  cms/api.py
  cms/migrations/0004_add_hero_titles_image_chooser.py
  cms/models.py
  cms/templates/home_page.html
  main/templates/base.html
  static/scss/home.scss
  static/scss/layout.scss
  static/scss/variables.scss
Labels: Waiting on Author

#45 asadiqbal08/Basic Product Detail Page
  cms/blocks.py
  cms/migrations/0005_product_detail_page.py
  cms/models.py
  cms/templates/product_page.html
  docker-compose.yml
  static/images/video.png
  static/scss/common.scss
  static/scss/layout.scss
  static/scss/product-details.scss
  static/scss/variables.scss
Labels: Waiting on Author

#46 Removed unneeded auth fields
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  authentication/serializers.py
  authentication/utils.py
  authentication/views_test.py
  fixtures/common.py
  main/settings.py
  main/urls.py
  static/js/components/UserMenu.js
  static/js/components/forms/EditProfileForm.js
  static/js/components/forms/EditProfileForm_test.js
  static/js/components/forms/ProfileFormFields.js
  static/js/components/forms/RegisterDetailsForm.js
  static/js/components/forms/RegisterDetailsForm_test.js
  static/js/components/forms/RegisterExtraDetailsForm.js
  static/js/components/forms/RegisterExtraDetailsForm_test.js
  static/js/containers/App.js
  static/js/containers/pages/profile/EditProfilePage.js
  static/js/containers/pages/profile/EditProfilePage_test.js
  static/js/containers/pages/profile/ViewProfilePage.js
  static/js/containers/pages/profile/ViewProfilePage_test.js
  static/js/containers/pages/register/RegisterDetailsPage.js
  static/js/containers/pages/register/RegisterDetailsPage_test.js
  static/js/containers/pages/register/RegisterExtraDetailsPage.js
  static/js/containers/pages/register/RegisterExtraDetailsPage_test.js
  static/js/containers/pages/register/RegisterPages.js
  static/js/flow/authTypes.js
  static/js/lib/auth.js
  static/js/lib/queries/auth.js
  static/js/lib/urls.js
  users/admin.py
  users/factories.py
  users/migrations/0014_remove_deprecated_profile_fields.py
  users/models.py
  users/models_test.py
  users/serializers.py
  users/serializers_test.py
  users/views_test.py
Labels: Needs Review

#37 added styling for header logo and sign-in/create account, hamburger links
  static/js/components/TopAppBar.js
  static/js/components/TopAppBar_test.js
  static/scss/top-app-bar.scss
  static/scss/user-menu.scss
  static/scss/variables.scss
Labels: Needs Review, Waiting on Author

#66 fix wagtail media upload error
  requirements.in
  requirements.txt
Labels: Needs Review

#68 Added dashboard message for users with no enrollments
  static/js/containers/pages/DashboardPage.js
  static/js/containers/pages/DashboardPage_test.js
  static/js/flow/courseTypes.js
  static/scss/layout.scss
Labels: Waiting on Author

#71 Added styling to pin footer to the bottom of the page
  static/scss/layout.scss
Labels: Waiting on Author

#63 Added API endpoint for creating user enrollments
  cms/migrations/0004_add_hero_titles_image_chooser.py
  courses/serializers.py
  courses/urls.py
  courses/views/v1/__init__.py
  courses/views_test.py
  mail/api.py
Labels: Waiting on Author

#65 excluded .container class from .auth-page elements
  cms/templates/product_page.html
  static/scss/product-details.scss
Labels: Waiting on Author

#54 Implement logged-ui in the site header
  static/js/components/TopAppBar.js
  static/js/components/TopAppBar_test.js
  static/js/components/UserMenu.js
  static/scss/top-app-bar.scss
  static/scss/user-menu.scss
Labels: Waiting on Author

#38 home page product section
  cms/migrations/0006_home_product_page.py
  cms/models.py
  cms/templates/home_page.html
  static/scss/course-cards.scss
  static/scss/home.scss
  static/scss/layout.scss
Labels: Waiting on Author

#77 fix: made dashboard accessible only when authenticated
  static/js/containers/App.js
Labels: Waiting on Author

#76 changed image src to valid image
  mail/templates/email_base.html
Labels: Waiting on Author

#88 fix home page feature products section
  cms/models.py
Labels: Needs Review

#81 Added course index page
  cms/constants.py
  cms/factories.py
  cms/migrations/0007_add_course_index_page.py
  cms/migrations/0008_move_pages_under_index.py
  cms/models.py
  cms/models_test.py
  cms/urls.py
  main/urls.py
Labels: Waiting on Author

#85 allow dot in course readable_id
  courses/migrations/0002_allow_period_in_readable_id.py
  courses/models.py
Labels: Waiting on Author

#92 Fixed home page product URLs
  cms/models.py
Labels: Waiting on Author

#89 add faculty section in the product page
  cms/blocks.py
  cms/migrations/0009_product_faculty_section.py
  cms/models.py
  cms/templates/home_page.html
  cms/templates/product_page.html
  static/scss/common.scss
  static/scss/course-cards.scss
  static/scss/layout.scss
  static/scss/product-faculty-members.scss
Labels: Waiting on Author

#93 Implemented enrollment and notification from product detail
  cms/models.py
  cms/models_test.py
  cms/templates/home_page.html
  cms/templates/product_page.html
  conftest.py
  courses/serializers.py
  courses/urls.py
  courses/views/v1/__init__.py
  courses/views_test.py
  main/constants.py
  main/features.py
  main/settings.py
  main/templates/base.html
  openedx/api.py
  openedx/api_test.py
  openedx/constants.py
  static/js/components/NotificationContainer.js
  static/js/components/NotificationContainer_test.js
  static/js/components/notifications/index.js
  static/js/constants.js
  static/js/containers/App.js
  static/js/containers/App_test.js
  static/js/containers/HeaderApp.js
  static/js/containers/HeaderApp_test.js
  static/js/lib/notificationsApi.js
  static/js/lib/notificationsApi_test.js
  static/js/lib/util.js
  static/js/lib/util_test.js
  static/scss/notification.scss
  static/scss/variables.scss
Labels: Waiting on Author

#113 Fixed issues with register API and recaptcha (#111)
  main/utils.py
  main/utils_test.py
  pytest.ini
Labels: Waiting on Author

#95 Add Embedded Video to Product Page
  cms/migrations/0010_coursepage_video_url.py
  cms/models.py
  cms/templates/product_page.html
  package.json
  static/js/entry/django.js
  static/scss/layout.scss
  static/scss/product-details.scss
  yarn.lock
Labels: Waiting on Author

#100 Fixed SignIn and Create Account style regression
  static/js/components/TopAppBar.js
  static/scss/top-app-bar.scss
Labels: Waiting on Author

#122 make product page faculty members optional
  cms/migrations/0010_coursepage_video_url.py
  cms/migrations/0011_product_faculty_members_optional.py
  cms/models.py
Labels: Waiting on Author

#119 Added setting to avoid name collisions in Wagtail
  app.json
  main/settings.py
Labels: Waiting on Author

#121 Update openedx configuration docs
  docs/configure_open_edx.md
Labels: Waiting on Author

#124 add dashboard, rename settings in the topbar menu
  static/js/components/TopAppBar.js
  static/js/components/TopAppBar_test.js
  static/js/components/UserMenu.js
Labels: Waiting on Author

#98 fix: styling and layout changes for dashboard, footer and product page
  cms/templates/product_page.html
  main/templates/footer.html
  static/scss/common.scss
  static/scss/dashboard.scss
  static/scss/footer.scss
  static/scss/layout.scss
  static/scss/product-details.scss
Labels: Waiting on Author

#133 Remove settings regarding reloading worker processes
  uwsgi.ini
Labels: Waiting on Author
