Repository mitodl/mitxonline, pull requests merged in 2022-08, with the labels that each got.

#737 add validation to block payment for the paid courserun
  ecommerce/api.py
  ecommerce/models.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  frontend/public/src/constants.js
  frontend/public/src/lib/notificationsApi.js
  main/constants.py
Labels: Needs Review

#753 fix: protect Product model from deletion
  ecommerce/admin.py
  ecommerce/db_utils.py
  ecommerce/migrations/0019_db_protect_product.py
  ecommerce/models.py
  ecommerce/models_test.py
Labels: Waiting on Author

#763 fix: enrollment upgrade from free to paid version
  courses/api.py
  courses/api_test.py
  courses/models.py
  courses/tasks.py
  courses/tasks_test.py
Labels: Needs Review

#760 add backfill migration for new table paid courserun
  courses/migrations/0013_backfill_paid_courserun.py
Labels: Needs Review

#772 770 - flexible pricing: too many decimal places
  ecommerce/serializers_test.py
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/lib/util.js
Labels: Needs Review

#771 Updates "skipped" to "denied" in flexible pricing.
  cms/models_test.py
  flexiblepricing/constants.py
  flexiblepricing/migrations/0017_update_flexible_pricing_rename_skipped_to_denied.py
  flexiblepricing/migrations/0018_alter_flexibleprice_status.py
  flexiblepricing/models.py
  flexiblepricing/models_test.py
  frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Labels: Needs Review

#757 734 - registration validate username against openedx
  authentication/pipeline/user_test.py
  authentication/views_test.py
  openedx/api.py
  openedx/api_test.py
  openedx/exceptions.py
  users/serializers.py
  users/serializers_test.py
Labels: Waiting on Author

#786 Fix Issue 767: More dates for course enrollment
  cms/templates/product_page.html
  frontend/public/scss/product-details.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/entry/django.js
Labels: Needs Review

#782 online-778 Order flexible prices by most recent first
  flexiblepricing/views/v0/__init__.py
Labels: Waiting on Author

#774 Restrict single active product per course ID
  ecommerce/migrations/0020_product_unique_object_id_validated.py
  ecommerce/models.py
  ecommerce/models_test.py
  flexiblepricing/mail_api.py
Labels: Needs Review

#788 Alter courserun.run_tag to a text field with max_length 100
  courses/admin.py
  courses/migrations/0014_alter_courserun_run_tag.py
  courses/models.py
Labels: Needs Review

#773 Add a scheduled task to process_refund_requests
  app.json
  main/settings.py
  main/settings_test.py
  requirements.in
  requirements.txt
  sheets/__init__.py
  sheets/apps.py
  sheets/tasks.py
  sheets/tasks_test.py
Labels: Waiting on Author

#787 Adds explicit binding of flexible price request forms to courseware objects
  cms/migrations/0020_flexiblepricingrequestform_selected_course.py
  cms/migrations/0021_flexiblepricingrequestform_selected_program.py
  cms/models.py
  cms/models_test.py
Labels: Waiting on Author

#758 add migration queries for courserun and enrollment
  micromasters_import/management/commands/queries/002_import_courserun.sql
  micromasters_import/management/commands/queries/003_import_enrollment.sql
Labels: Needs Review

#802 Switch some settings to use urljoin
  main/settings.py
Labels: Needs Review

#800 Updates status filtering to send an undefined if there's nothing selected
  .gitignore
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Labels: Waiting on Author

#766 Adds program support to the dashboard
  courses/serializers.py
  ecommerce/serializers.py
  frontend/public/package.json
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/ProgramEnrollmentCard.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/queries/enrollment.js
  yarn.lock
Labels: Needs Review

#807 Updates flexible pricing to add a unique constraint on submissions
  cms/factories.py
  cms/models.py
  cms/models_test.py
  courses/models.py
  flexiblepricing/api_test.py
  flexiblepricing/migrations/0019_add_unique_user_courseware_to_flexiblepricing.py
  flexiblepricing/models.py
  flexiblepricing/models_test.py
Labels: Waiting on Author

#798 More Dates: Tooltip title text, style, irrelevant dates bug fixes #767
  cms/models.py
  cms/models_test.py
  cms/templates/product_page.html
  frontend/public/scss/product-details.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/factories/course.js
Labels: Needs Review

#819 Remove learners tab from staff dashboard
  frontend/staff-dashboard/src/App.tsx
Labels: Needs Review

#801 Add financial aid migration query and tier program mapping table
  micromasters_import/admin.py
  micromasters_import/management/commands/queries/004_import_financial_aid.sql
  micromasters_import/migrations/0002_programtiers_pk_mapping.py
  micromasters_import/models.py
Labels: Waiting on Author

#823 818 bug unique object id validated contraint on product makes it impossible to add products across different content types
  ecommerce/migrations/0023_alter_index_unique_object_id_validated.py
  ecommerce/models.py
  ecommerce/models_test.py
Labels: Waiting on Author

#827 Fixes scrolling when the program drawer has items that extend beyond the bottom of the screen
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/ProgramEnrollmentDrawer.js
Labels: Needs Review

#814 Adds some more time to the docker-compose watches
  docker-compose.yml
Labels: Waiting on Author

#781 online-779 Display `Documents in order` as default
  frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
Labels: Needs Review

#836 Fixes empty dashboard issue if there's no CMS page for a course
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/lib/courseApi.js
Labels: Waiting on Author

#835 Update refine callback URL to remove double slash
  docs/source/configuration/refine_admin.rst
Labels: Waiting on Author

#846 Online-829 Open program drawer when program title is clicked
  frontend/public/src/components/ProgramEnrollmentCard.js
Labels: Needs Review

#845 Online-839 Improve Financial Assistance Request List View
  flexiblepricing/serializers.py
  frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
  frontend/staff-dashboard/src/interfaces/index.d.ts
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
  frontend/staff-dashboard/src/styles/antd.less
  frontend/staff-dashboard/src/utils.ts
Labels: Needs Review

#851 Online-841 Adds support for Financial Assistance Request denied email
  flexiblepricing/mail_api.py
  flexiblepricing/tasks.py
  flexiblepricing/tasks_test.py
  flexiblepricing/views/v0/__init__.py
  frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
  frontend/staff-dashboard/src/constants.ts
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
  frontend/staff-dashboard/src/styles/antd.less
Labels: Needs Review

#820 feat: add course run upgrade deadline
  courses/admin.py
  courses/factories.py
  courses/migrations/0017_add_upgrade_deadline.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  ecommerce/api.py
  ecommerce/models.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/constants.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/factories/course.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/notificationsApi.js
  main/constants.py
Labels: Waiting on Author

#740 feat: Add Certificate Template using Wagtail CMS
  cms/blocks.py
  cms/constants.py
  cms/forms.py
  cms/migrations/0023_certificateindexpage_certificatepage_signatoryindexpage_signatorypage.py
  cms/models.py
  cms/templates/certificate_page.html
  courses/admin.py
  courses/migrations/0018_courseruncertificate.py
  courses/models.py
  frontend/public/scss/certificates/certificate.scss
  frontend/public/scss/layout.scss
  static/images/certificates/certificate-logo.png
  static/images/certificates/icon-facebook.svg
  static/images/certificates/icon-linkedin.svg
  static/images/certificates/icon-print.svg
  static/images/certificates/icon-twitter.svg
Labels: Waiting on Author

#863 fix: datetime issue in flexible price form
  cms/models.py
Labels: Waiting on Author

#838 Purges the Fastly cache for a page once the page has been modified
  app.json
  cms/api.py
  cms/apps.py
  cms/signalreceivers.py
  cms/tasks.py
  main/settings.py
  requirements.in
  requirements.txt
Labels: Needs Review

#858 Flexible Pricing: adds text to display when the request is assigned a $0 tier
  cms/migrations/0023_add_zero_discount_form_field.py
  cms/migrations/0024_merge_20220817_2047.py
  cms/models.py
  cms/models_test.py
  cms/templates/flexiblepricing/flexible_pricing_request_form.html
Labels: Waiting on Author

#861 Online-860 Calculate flexible price discount instead of using BasketDiscount
  ecommerce/api.py
  ecommerce/views/v0/__init__.py
Labels: Waiting on Author

#817 806: ecommerce implement a cybersource notification api endpoint
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/urls.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  fixtures/common.py
Labels: Waiting on Author

#855 811: need financial assistance link on the checkout page
  cms/models.py
  cms/serializers.py
  cms/serializers_test.py
  courses/serializers_test.py
  frontend/public/src/containers/pages/checkout/CartPage.js
  frontend/public/src/flow/cartTypes.js
Labels: Needs Review

#878 Check for program page before checking for child pages
  cms/serializers.py
  cms/serializers_test.py
Labels: Needs Review

#875 Online-868 Hide enrolment button for anonymous users
  courses/api.py
  courses/views/v1/__init__.py
  flexiblepricing/api.py
  flexiblepricing/api_test.py
  frontend/public/src/containers/ProductDetailEnrollApp.js
Labels: Waiting on Author

#874 fix: active products to cart only
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  flexiblepricing/mail_api.py
Labels: Waiting on Author

#848 Ecommerce: adds activation and expiration dates to discount codes
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/migrations/0024_add_discount_action_dates.py
  ecommerce/models.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  flexiblepricing/api.py
  flexiblepricing/api_test.py
  frontend/public/src/constants.js
  frontend/public/src/lib/notificationsApi.js
  main/constants.py
Labels: Waiting on Author

#880 Fixes some issues with the Fastly API code
  cms/management/commands/purge_fastly_cache.py
  cms/tasks.py
  requirements.in
  requirements.txt
Labels: Needs Review

#877 872: checkout remove clear discount and a few other tweaks
  ecommerce/discounts_test.py
  ecommerce/serializers.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  frontend/public/src/components/CartItemCard.js
  frontend/public/src/components/OrderSummaryCard.js
  frontend/public/src/containers/pages/checkout/CartPage.js
  frontend/public/src/lib/queries/cart.js
Labels: Needs Review

#856 Get certificate at reduced price
  cms/templates/flexiblepricing/flexible_pricing_request_form.html
  courses/models.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
Labels: Waiting on Author

#890 Adds currency code descriptions; makes sure invalid codes are removed
  flexiblepricing/api.py
  flexiblepricing/api_test.py
  flexiblepricing/constants.py
  flexiblepricing/management/commands/update_exchange_rates.py
  flexiblepricing/management/commands/update_exchange_rates_test.py
  flexiblepricing/tasks.py
  main/constants.py
Labels: Waiting on Author

#891 Update flexible pricing approval email to eliminate errors when sending
  ecommerce/models.py
  flexiblepricing/constants.py
  flexiblepricing/mail_api.py
Labels: Waiting on Author

#892 Learner and anonymous certificate view- issue #692 #693
  cms/api.py
  cms/commands_test.py
  cms/factories.py
  cms/management/commands/configure_wagtail.py
  cms/models.py
  cms/serializers_test.py
  courses/factories.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views_test.py
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/flow/courseTypes.js
  main/templates/base.html
  main/templatetags/startswith.py
Labels: Needs Review

#898 Adds setup command to bootstrap financial aid for DEDP
  ecommerce/models.py
  flexiblepricing/management/commands/configure_for_dedp.py
  flexiblepricing/management/commands/configure_for_dedp_test.py
Labels: Needs Review

#899 fix: basket checkout with zero value
  ecommerce/api.py
  ecommerce/views_test.py
Labels: Waiting on Author

#882 869 add unique key to ecommerce line and ecommerce transaction
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/migrations/0024_line_unique_order_purchased_object.py
  ecommerce/migrations/0025_transaction_transaction_id.py
  ecommerce/migrations/0026_backfill_transaction_id.py
  ecommerce/migrations/0027_alter_transaction_transaction_id.py
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/serializers_test.py
  ecommerce/views_test.py
Labels: Needs Review

#888 884: dashboard design update
  cms/migrations/0025_modify_feature_image_blank.py
  cms/models.py
  courses/serializers.py
  courses/serializers_test.py
  flexiblepricing/api.py
  flexiblepricing/api_test.py
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/EnrollmentRoleTag.js
  frontend/public/src/components/GetCertificateButton.js
  frontend/public/src/components/ProgramEnrollmentCard.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/factories/course.js
Labels: Needs Review

#901 Fixes nav issues when a course date is selected
  cms/templates/product_page.html
  frontend/public/scss/product-details.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
Labels: Needs Review

#900 add error log for transactions' reason code any number other than 100
  ecommerce/api.py
Labels: Needs Review

#902 fix migration conflicts and discount tests
  ecommerce/migrations/0025_line_unique_order_purchased_object.py
  ecommerce/migrations/0026_transaction_transaction_id.py
  ecommerce/migrations/0027_backfill_transaction_id.py
  ecommerce/migrations/0028_alter_transaction_transaction_id.py
  ecommerce/models.py
  ecommerce/views_test.py
Labels: Needs Review

#859 Add queries to migrate order, line and transaction from MicroMaster
  ecommerce/admin.py
  ecommerce/migrations/0029_add_partially_refunded_state_to_order.py
  ecommerce/models.py
  micromasters_import/management/commands/queries/005_import_order.sql
  micromasters_import/management/commands/queries/006_import_line.sql
  micromasters_import/management/commands/queries/007_import_transation.sql
Labels: Waiting on Author

#908 905: dashboard overflow menu ⋮ accessibility
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrollmentRoleTag.js
  frontend/public/src/components/ProgramEnrollmentCard.js
Labels: Needs Review, Waiting on Author

#722 feat: poll grades and generate certificates
  app.json
  courses/admin.py
  courses/api.py
  courses/api_test.py
  courses/factories.py
  courses/migrations/0019_add_is_self_paced_course_run.py
  courses/models.py
  courses/models_test.py
  courses/tasks.py
  courses/tasks_test.py
  courses/utils.py
  main/settings.py
  openedx/constants.py
Labels: Waiting on Author

#917 Program Flexible Pricing approval page
  cms/templates/flexiblepricing/flexible_pricing_request_form.html
Labels: Needs Review
