Repository mitodl/mitxonline, pull requests merged in 2022-12, with the labels that each got.

#1241 Change ubuntu-latest to ubuntu-20.04 on all github actions yml files
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .github/workflows/production.yml
  .github/workflows/release-candiate.yml
Labels: Needs Review

#1237 Adds program record functionality
  .pre-commit-config.yaml
  courses/admin.py
  courses/factories.py
  courses/mail_api.py
  courses/mail_api_test.py
  courses/messages.py
  courses/migrations/0023_add_partnerschool_model.py
  courses/migrations/0024_add_record_share_model.py
  courses/models.py
  courses/serializers.py
  courses/tasks.py
  courses/tasks_test.py
  courses/templates/mail/partner_school_sharing/body.html
  courses/templates/mail/partner_school_sharing/subject.txt
  courses/urls.py
  courses/views/v1/__init__.py
  frontend/public/scss/common.scss
  frontend/public/scss/layout.scss
  frontend/public/scss/learner-records.scss
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  frontend/public/src/constants.js
  frontend/public/src/containers/App.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/pages/records/LearnerRecordsPage.js
  frontend/public/src/factories/course.js
  frontend/public/src/flow/authTypes.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/flow/declarations.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
  frontend/public/src/lib/queries/enrollment.js
  frontend/public/src/lib/urls.js
  frontend/public/src/lib/util.js
  main/features.py
  main/urls.py
  main/utils.py
  main/utils_test.py
Labels: Needs Review, Waiting on Author

#1249 Adds "reference_number" to the searchable fields in order admins
  ecommerce/admin.py
Labels: Waiting on Author

#1244 Updates program drawer to handle empty requirements trees; adds function to check for invalid trees
  app.json
  courses/api.py
  courses/api_test.py
  courses/management/commands/check_program_requirements.py
  courses/tasks.py
  docs/source/commands/check_program_requirements.rst
  docs/source/commands/index.rst
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  main/settings.py
Labels: Needs Review

#1239 fix: program certificate creation should use ProgramRequirement tree
  courses/api.py
  courses/api_test.py
  courses/factories.py
  courses/migrations/0025_alter_courseruncertificate_course_run.py
  courses/models.py
  courses/signals.py
  courses/signals_test.py
  courses/utils.py
  courses/utils_test.py
Labels: Waiting on Author

#1248 Fixes the URL in the partner school email
  courses/mail_api.py
  courses/mail_api_test.py
Labels: Needs Review

#1256 Adds courserun importing from edX (like sync_courserun, but moreso)
  courses/management/commands/import_courserun.py
  docs/source/commands/import_courserun.rst
  docs/source/commands/index.rst
Labels: Needs Review

#1268 Flipping the default for `for_flexible_pricing` from True to False
  ecommerce/migrations/0030_alter_discount_for_flexible_pricing.py
  ecommerce/models.py
Labels: Waiting on Author

#1267 1253: dashboard courses and programs tabs aren't screen reader accessible
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/containers/pages/DashboardPage.js
Labels: Waiting on Author

#1274 Removes program readable ID from the card
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#1262 Run command to create initial revisions in `configure_instance`
  main/management/commands/configure_instance.py
Labels: Waiting on Author

#1258 add MM program certificate migration script
  micromasters_import/README.md
  micromasters_import/admin.py
  micromasters_import/management/commands/queries/012_import_program_certificates.sql
  micromasters_import/migrations/0004_add_program_certificate_revision.py
  micromasters_import/models.py
Labels: Waiting on Author

#1279 1252: dashboard course should not be in progress and ended at the same time
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
Labels: Needs Review

#1278 Program drawer remove not enrolled
  frontend/public/src/components/ProgramEnrollmentDrawer.js
Labels: Needs Review

#1277 Updates program UI to enable unenrollments
  courses/urls.py
  courses/views/v1/__init__.py
  courses/views_test.py
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/EnrolledProgramList.js
  frontend/public/src/factories/course.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/queries/enrollment.js
Labels: Needs Review

#1225 Edx verified force enrollment after enrollment end date
  courses/api.py
  courses/api_test.py
  courses/management/commands/create_verified_enrollment.py
  openedx/api.py
  openedx/api_test.py
Labels: Waiting on Author

#1260 feat: management command for creating, revoking program certificates
  courses/api.py
  courses/api_test.py
  courses/management/commands/manage_program_certificates.py
  courses/management/commands/test_manage_program_certificate.py
  fixtures/common.py
Labels: Waiting on Author

#1261 fix: certificate template improvements
  cms/templates/certificate_page.html
  main/templates/copyright.html
  main/templates/footer.html
Labels: Needs Review

#1284 Updates course run and program certificate models to limit choices just to certificate pages in admin
  cms/models_test.py
  courses/migrations/0026_alter_courseruncertificate_certificate_page_revision.py
  courses/migrations/0027_alter_programcertificate_certificate_page_revision.py
  courses/migrations/0028_alter_certificate_models_make_page_revision_blankable.py
  courses/models.py
  courses/models_test.py
Labels: Waiting on Author

#1282 fix: program certificate link text
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#1281 Updates the program drawer to use the requirements tree
  courses/serializers.py
  courses/serializers_test.py
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  frontend/public/src/factories/course.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
Labels: Needs Review

#1297 Fixed program info card to render course details link properly
  cms/serializers.py
  cms/serializers_test.py
  courses/serializers_test.py
  frontend/public/src/components/ProgramCourseInfoCard.js
  frontend/public/src/flow/cmsTypes.js
Labels: Waiting on Author

#1296 Updates button styling to sync border widths; updates close button on drawer
  frontend/public/scss/common.scss
  frontend/public/scss/dashboard.scss
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  static/images/close-drawer.png
Labels: Waiting on Author

#1305 fix: Fix courseware URL in command
  courses/management/commands/import_courserun.py
Labels: Needs Review

#1303 fix: don't show programs tab if user isn't enrolled in a program
  frontend/public/src/containers/pages/DashboardPage.js
Labels: Needs Review

#1301 fix:dashboard confirmation dialog for unenrolling from courses
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
Labels: Needs Review

#1299 Fixes the course model to round the grade (fixes a flaky test)
  courses/models.py
Labels: Needs Review

#1307 Fixes import_courserun to handle courses that exist already
  courses/management/commands/import_courserun.py
Labels: Waiting on Author
