Repository mitodl/mitxonline, pull requests merged in 2022-11, with the labels that each got.

#1184 Add missing import
  courses/forms.py
Labels: Needs Review

#1176 Adds wrapper command to bootstrap a fresh MITxOnline instance
  README.md
  docs/source/commands/configure_instance.rst
  docs/source/commands/create_courseware.rst
  docs/source/commands/create_courseware_page.rst
  docs/source/commands/create_product.rst
  docs/source/commands/create_user.rst
  docs/source/commands/index.rst
  docs/source/configuration/ecommerce.rst
  docs/source/configuration/index.rst
  docs/source/configuration/quickstart.rst
  docs/source/configuration/refine_admin.rst
  docs/source/ecommerce/flexible_pricing.rst
  docs/source/index.rst
  ecommerce/management/commands/create_product.py
  main/management/commands/configure_instance.py
  users/management/commands/create_user.py
Labels: Waiting on Author

#1169 add a migration to backfill PaidCourseRun for the legacy orders
  micromasters_import/management/commands/queries/010_backfill_paidcourserun.sql
Labels: Needs Review

#1187 Add honor code link to account creation dialog
  frontend/public/src/components/forms/RegisterEmailForm.js
  frontend/public/src/lib/urls.js
Labels: Waiting on Author

#1194 Enhance Product admin search and List display
  courses/models.py
  ecommerce/admin.py
Labels: Waiting on Author

#1197 add migration to import program enrollments from MicroMaster
  micromasters_import/README.md
  micromasters_import/management/commands/queries/011_import_program_enrollments.sql
Labels: Needs Review

#1204 Fix accidental deletion of requirements
  courses/serializers.py
  courses/serializers_test.py
Labels: Needs Review

#1211 Updates ol-django requirements
  requirements.in
  requirements.txt
  test_requirements.txt
Labels: Needs Review

#1215 Adds some code to walk the requirements tree if there are nested operators
  courses/serializers.py
Labels: Waiting on Author

#1209 1206 dashboard course detail and view certificate links are too close together
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#1223 Added some checks to ensure there is a requirements tree before walking it
  courses/serializers.py
Labels: Needs Review

#1228 fixing list formatting in generate_discount_code.rst
  docs/source/commands/generate_discount_code.rst
Labels: documentation, Waiting on Author

#1230 1207 accessibility more dates popup on course pages lacks keyboard controls
  cms/templates/product_page.html
  frontend/public/scss/product-details.scss
  frontend/public/src/entry/django.js
Labels: Needs Review
