Repository mitodl/mitxonline, pull requests merged in 2022-09, with the labels that each got.

#922 Hide description if certificate is also hidden
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#923 fix: certificate error when end_date is not set
  courses/api.py
  courses/api_test.py
Labels: Waiting on Author

#927 Adds OFAC messaging to the bottom of the course about page
  cms/templates/product_page.html
  frontend/public/scss/product-details.scss
Labels: Waiting on Author

#933 Fixes API error when learner is enrolled in a courserun with no related page
  courses/serializers.py
Labels: Waiting on Author

#928 Adds a feature flag (overridable by URL) for the program UI
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/flow/declarations.js
  frontend/public/src/lib/util.js
  main/features.py
  main/utils.py
  main/utils_test.py
Labels: Waiting on Author

#914 Adds accessibility attributes to make the program drawer work better with screen readers
  frontend/public/src/components/ProgramEnrollmentCard.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
Labels: Waiting on Author, accessibility

#929 910 dashboard doesnt refresh when user unenrolls from course in a program
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/lib/queries/enrollment.js
Labels: Needs Review

#847 Refund order based on id or reference number
  app.json
  conftest.py
  ecommerce/api.py
  ecommerce/api_test.py
  main/settings.py
  main/settings_test.py
  pytest.ini
  requirements.in
  requirements.txt
  sheets/plugins.py
Labels: Waiting on Author

#938 fix 500 error on external course checkout
  ecommerce/views/v0/__init__.py
Labels: Waiting on Author

#948 Fix failing test_order_refund_success_with_ref_num
  ecommerce/api_test.py
Labels: Waiting on Author

#946 Online-943 Update course start string
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
Labels: Waiting on Author

#958 Online-941 Filter zero value discounts on checkout
  ecommerce/serializers.py
  ecommerce/serializers_test.py
Labels: Needs Review

#947 Adds a check to make sure flexible pricing forms have the right fields in them
  cms/signalreceivers.py
  flexiblepricing/utils.py
  flexiblepricing/utils_test.py
Labels: Needs Review, Waiting on Author

#919 842: sync-coursrun-upgrade-deadline-with-edx
  courses/api.py
  courses/api_test.py
  courses/tasks.py
  openedx/api.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#955 944 about page design tweaks
  cms/templates/home_page.html
  cms/templates/product_page.html
  frontend/public/scss/auth.scss
  frontend/public/scss/cart.scss
  frontend/public/scss/common.scss
  frontend/public/scss/course-cards.scss
  frontend/public/scss/dashboard.scss
  frontend/public/scss/product-details.scss
  frontend/public/scss/product-faculty-members.scss
  frontend/public/scss/top-app-bar.scss
  frontend/public/scss/user-menu.scss
  frontend/public/scss/variables.scss
  frontend/public/src/components/OrderSummaryCard.js
  frontend/public/src/components/forms/ApplyCouponForm.js
Labels: Needs Review

#893 add query to migrate grades from MicroMaster
  micromasters_import/management/commands/queries/003_import_enrollment.sql
  micromasters_import/management/commands/queries/008_import_combined_final_grade.sql
Labels: Needs Review

#959 Adds a refresh button to the Flexible Pricing Request list page in staff dashboard
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Labels: Needs Review, Waiting on Author

#966 Updates product pages to display approved flexible pricing amounts if one exists
  cms/models.py
  cms/models_test.py
  cms/templates/product_page.html
  courses/models.py
  ecommerce/models.py
  ecommerce/models_test.py
  flexiblepricing/api.py
Labels: Needs Review

#965 adding course/program as filter on flexible pricing staff dashboard
  courses/serializers.py
  courses/serializers_test.py
  flexiblepricing/views/v0/__init__.py
  frontend/staff-dashboard/src/interfaces/index.d.ts
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Labels: Waiting on Author

#969 942: unauthorized user can access staff dashboard
  frontend/staff-dashboard/src/App.tsx
  frontend/staff-dashboard/src/hooks/useAuthProvider.ts
  frontend/staff-dashboard/src/index.tsx
  main/oidc_provider_settings.py
  main/settings.py
Labels: Waiting on Author

#897 feat: Add command for certificate management
  courses/api.py
  courses/api_test.py
  courses/management/commands/manage_certificates.py
  courses/management/commands/test_manage_certificate.py
  courses/utils.py
Labels: Waiting on Author

#970 Update justifications based on action in refine, allow it to be blank for reset
  flexiblepricing/migrations/0020_alter_flexibleprice_justification.py
  flexiblepricing/models.py
  frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
  frontend/staff-dashboard/src/constants.ts
Labels: Waiting on Author

#979 Fix renovate config
  renovate.json5
Labels: Needs Review

#978 get complete list of courseware in flexible pricing request
  flexiblepricing/serializers.py
  flexiblepricing/urls.py
  flexiblepricing/views/v0/__init__.py
  frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Labels: Needs Review

#903 Versioning of certificate template
  cms/models.py
  cms/models_test.py
  courses/admin.py
  courses/api_test.py
  courses/factories.py
  courses/migrations/0020_courseruncertificate_certificate_page_revision.py
  courses/models.py
  courses/serializers_test.py
  courses/views_test.py
Labels: Needs Review

#973 display certificate start and end date on template
  cms/templates/certificate_page.html
  courses/models.py
Labels: Needs Review

#1005 Fix factory-boy package name and pin
  test_requirements.txt
Labels: Needs Review

#974 data migration for certificate index page
  cms/migrations/0026_certificate_index_page_slug.py
Labels: Needs Review

#1000 Adds an email message that is sent when an order is refunded.
  courses/models.py
  ecommerce/mail_api.py
  ecommerce/mail_api_test.py
  ecommerce/messages.py
  ecommerce/models.py
  ecommerce/tasks.py
  ecommerce/tasks_test.py
  ecommerce/templates/mail/order_refund_message/body.html
  ecommerce/templates/mail/order_refund_message/subject.txt
Labels: Waiting on Author

#992 fix: text change to OFAC disclaimer
  cms/templates/product_page.html
Labels: Needs Review

#1018 780: Flexible Pricing: Resetting two Flexible Pricing Requests from the same user will spam their emai
  frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
Labels: Needs Review

#1015 Bump google sheets versions
  app.json
  requirements.in
  requirements.txt
Labels: Needs Review

#1020 934 add user to sync enrollments with edx error log and pass send_default_pii to sentry configuration
  main/sentry.py
  main/settings.py
  openedx/api.py
Labels: Waiting on Author

#1029 Fixes duplicate key error when returning to cart using back button
  ecommerce/api.py
  ecommerce/views/v0/__init__.py
Labels: Needs Review

#1049 Updates the order fulfillment code to wait for the transaction to complete before sending message
  ecommerce/mail_api_test.py
  ecommerce/models.py
  ecommerce/tasks_test.py
Labels: Needs Review

#1055 Cleans up some extraneous messaging when running management commands
  ecommerce/serializers.py
  main/settings.py
Labels: Needs Review

#1052 Online-1048 Add top margin for footer
  frontend/public/scss/footer.scss
Labels: Waiting on Author

#1056 1036 enrolled button on about page links to course before it has started
  frontend/public/scss/common.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
Labels: Needs Review

#1028 update payment response reason code to log error for 1xx
  ecommerce/api.py
Labels: Needs Review

#1043 Adding management command to create products for DEDP program
  flexiblepricing/management/commands/create_product_for_program_courses.py
  flexiblepricing/management/commands/create_product_for_program_courses_test.py
Labels: Waiting on Author

#1057 1051: Don't display "active" on the dashboard when it is past the course run's course_end date
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/lib/courseApi.js
Labels: Waiting on Author

#1065 Online-1035 Display upgrade dialog when Ecommerce enabled
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
Labels: Needs Review

#1039 Adds management command to generate enrollment codes for legacy learners
  ecommerce/management/__init__.py
  ecommerce/management/commands/__init__.py
  ecommerce/management/commands/find_paid_unenrolled_learners.py
  ecommerce/management/commands/generate_legacy_enrollment_codes.py
Labels: Waiting on Author

#949 Changes the receipt email subject
  ecommerce/templates/mail/product_order_receipt/subject.txt
Labels: Needs Review

#1060 1044: when referring to a course in email don't include the full course
  courses/models.py
  ecommerce/mail_api.py
  flexiblepricing/mail_api.py
Labels: Needs Review

#1062 add webpack-bundle-analyzer
  frontend/public/package.json
  frontend/public/webpack.config.js
  yarn.lock
Labels: Needs Review

#1059 Upgrade legacy learners that paid and are enrolled, have exam attempt
  courses/management/commands/upgrade_eligible_users.py
Labels: Needs Review

#1063 remove unused variables + update eslint config to prevent them in future
  frontend/public/.eslintrc
  frontend/public/src/components/AnonymousMenu.js
  frontend/public/src/components/CartItemCard.js
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/Expandable.js
  frontend/public/src/components/GetCertificateButton.js
  frontend/public/src/components/InstituteLogo.js
  frontend/public/src/components/Loader.js
  frontend/public/src/components/OrderSummaryCard.js
  frontend/public/src/components/ProgramEnrollmentCard.js
  frontend/public/src/components/ReceiptPageDetailCard.js
  frontend/public/src/components/TopAppBar.js
  frontend/public/src/components/TopAppBar_test.js
  frontend/public/src/components/UserMenu.js
  frontend/public/src/components/forms/ApplyCouponForm.js
  frontend/public/src/components/forms/ApplyCouponForm_test.js
  frontend/public/src/components/forms/ChangeEmailForm.js
  frontend/public/src/components/forms/ChangePasswordForm.js
  frontend/public/src/components/forms/ProfileFormFields.js
  frontend/public/src/components/forms/ResetPasswordForm.js
  frontend/public/src/components/notifications/index_test.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/containers/pages/DashboardPage_test.js
  frontend/public/src/containers/pages/checkout/CartPage.js
  frontend/public/src/containers/pages/checkout/OrderHistory.js
  frontend/public/src/containers/pages/checkout/OrderReceiptPage_test.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordPage.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordPage_test.js
  frontend/public/src/containers/pages/profile/EditProfilePage_test.js
  frontend/public/src/containers/pages/register/RegisterConfirmPage.js
  frontend/public/src/containers/pages/register/RegisterConfirmPage_test.js
  frontend/public/src/containers/pages/register/RegisterConfirmSentPage_test.js
  frontend/public/src/containers/pages/register/RegisterEmailPage_test.js
  frontend/public/src/containers/pages/settings/AccountSettingsPage.js
  frontend/public/src/containers/pages/settings/EmailConfirmPage_test.js
  frontend/public/src/factories/course.js
  frontend/public/src/lib/api.js
  frontend/public/src/lib/api_test.js
  frontend/public/src/lib/auth.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
  frontend/public/src/lib/queries/enrollment.js
  frontend/public/src/lib/util_test.js
  frontend/public/src/util/integration_test_helper.js
Labels: Needs Review

#1079 fix: show zero for negative prices
  frontend/public/src/lib/util.js
  frontend/public/src/lib/util_test.js
Labels: Needs Review

#1068 update local only enrollments error to filter out unenrolled
  openedx/api.py
Labels: Needs Review

#1081 Fix a small bug in upgrade_eligible_users
  courses/management/commands/upgrade_eligible_users.py
Labels: Needs Review

#1080 Adding duplicate checking and expiration date on generated enrollment codes
  ecommerce/management/commands/generate_legacy_enrollment_codes.py
Labels: Needs Review
