Repository mitodl/mitxonline, pull requests merged in 2023-05, with the labels that each got.

#1582 Update decode uri component from 0.2.0 to 0.2.2
  frontend/public/src/lib/api_test.js
  yarn.lock
Labels: Needs Review

#1578 Updates fields that are sent to edX and adds profile sync
  openedx/api.py
  openedx/api_test.py
  openedx/exceptions.py
  openedx/management/commands/update_edx_profiles.py
  users/models.py
Labels: Needs Review

#1586 Throw an error if the user manages to get to the registration screen with the same email
  frontend/public/src/containers/pages/register/RegisterDetailsPage.js
  users/serializers.py
  users/serializers_test.py
Labels: Needs Review

#1589 Fixes us_state to return None if there's no state; adds a test for that
  users/models.py
  users/models_test.py
Labels: Waiting on Author

#1584 Add AR Argentina
  flexiblepricing/data/country_income_thresholds.csv
Labels: Needs Review

#1579 1573 sync extended profile data to hubspot
  docs/source/configuration/hubspot.rst
  hubspot_sync/api.py
  hubspot_sync/api_test.py
  hubspot_sync/management/commands/configure_hubspot_properties.py
Labels: Waiting on Author

#1599 config: Update renovate config
  renovate.json
  renovate.json5
Labels: DevOps, Needs Review

#1602 Removes a stray aria-hidden attribute
  frontend/public/src/components/ProgramEnrollmentDrawer.js
Labels: Waiting on Author, accessibility

#1606 Update Wagtail to v5
  cms/api.py
  cms/api_test.py
  cms/blocks.py
  cms/factories.py
  cms/migrations/0002_course_page.py
  cms/migrations/0003_resourcepage.py
  cms/migrations/0005_product_detail_page.py
  cms/migrations/0009_product_faculty_section.py
  cms/migrations/0011_product_faculty_members_optional.py
  cms/migrations/0012_product_description_help_text.py
  cms/migrations/0014_make_product_mandatory_fields_required.py
  cms/migrations/0017_add_flexible_pricing_request_form.py
  cms/migrations/0020_add_productpage_and_base_tables.py
  cms/migrations/0023_add_zero_discount_form_field.py
  cms/migrations/0023_certificateindexpage_certificatepage_signatoryindexpage_signatorypage.py
  cms/migrations/0026_certificate_index_page_slug.py
  cms/migrations/0027_wagtail_v5_upgrade.py
  cms/models.py
  cms/models_test.py
  cms/signalreceivers.py
  cms/urls.py
  cms/wagtail_hooks.py
  courses/migrations/0020_courseruncertificate_certificate_page_revision.py
  courses/migrations/0021_programcertificate.py
  courses/migrations/0026_alter_courseruncertificate_certificate_page_revision.py
  courses/migrations/0027_alter_programcertificate_certificate_page_revision.py
  courses/migrations/0028_alter_certificate_models_make_page_revision_blankable.py
  courses/models.py
  courses/models_test.py
  flexiblepricing/migrations/0005_add_flexible_pricing_request_form.py
  flexiblepricing/migrations/0008_flexiblepricingrequestform_guest_text.py
  flexiblepricing/migrations/0009_flexiblepricingrequestform_more_textboxes.py
  flexiblepricing/migrations/0021_alter_flexiblepricingrequestsubmission_form_data.py
  main/settings.py
  main/urls.py
  main/utils.py
  micromasters_import/migrations/0003_course_certificate_id_mapping.py
  micromasters_import/migrations/0004_add_program_certificate_revision.py
  micromasters_import/models.py
  requirements.in
  requirements.txt
Labels: Needs Review

#1609 1605: get certificate button on approved flexible price leads to empty cart
  cms/models.py
  cms/models_test.py
  cms/templates/flexiblepricing/flexible_pricing_request_form.html
Labels: Needs Review

#1607 Use new hubspot_api version and try to sync contacts individually if a batched sync chunk fails
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  hubspot_sync/tasks.py
  hubspot_sync/tasks_test.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1616 Fix flexible pricing page for programs
  cms/models.py
  cms/models_test.py
  cms/templates/flexiblepricing/flexible_pricing_request_form.html
Labels: Needs Review

#1624 Update mitol/hubspot_api app
  hubspot_sync/tasks_test.py
  requirements.in
  requirements.txt
Labels: Waiting on Author

#1621 Expands edX profile sync.
  openedx/api.py
  openedx/api_test.py
  openedx/tasks.py
  users/models.py
  users/models_test.py
  users/views.py
  users/views_test.py
Labels: Needs Review

#1628 1627: improve hubspot sync script to handle large numbers of users
  hubspot_sync/api.py
  hubspot_sync/api_test.py
  hubspot_sync/tasks.py
  main/settings.py
  users/admin.py
  users/migrations/0023_user_hubspot_sync_datetime.py
  users/models.py
Labels: Waiting on Author

#1604 Adding google sheets deferrals library
  app.json
  main/settings.py
  requirements.in
  requirements.txt
  sheets/plugins.py
  sheets/tasks.py
  sheets/tasks_test.py
Labels: Needs Review

#1635 Remove scheduled cron task to sync all HubSpot contacts
  main/settings.py
Labels: Needs Review

#1636 Add row header to order history table
  frontend/public/src/containers/pages/checkout/OrderHistory.js
Labels: Waiting on Author

#1376 Incorporates changes to make MITxOnline work with Tutor
  README.md
  docker-compose.yml
  docs/source/commands/configure_instance.rst
  docs/source/configuration/index.rst
  docs/source/configuration/refine_admin.rst
  docs/source/configuration/tutor.rst
  main/management/commands/configure_instance.py
Labels: Needs Review

#1637 update google-sheets-deferrals
  requirements.in
  requirements.txt
Labels: Needs Review

#1631 Adds bulk code generation to staff-dashboard
  ecommerce/api.py
  ecommerce/management/commands/generate_discount_code.py
  ecommerce/migrations/0034_add_bulk_field_to_discounts.py
  ecommerce/models.py
  ecommerce/serializers.py
  ecommerce/views/v0/__init__.py
  ecommerce/views_test.py
  frontend/staff-dashboard/package.json
  frontend/staff-dashboard/src/App.tsx
  frontend/staff-dashboard/src/components/discounts/bulk_discount_results.tsx
  frontend/staff-dashboard/src/components/discounts/bulk_discounts.tsx
  frontend/staff-dashboard/src/interfaces/index.d.ts
  frontend/staff-dashboard/src/pages/discounts/bulk_create.tsx
  frontend/staff-dashboard/src/pages/discounts/index.tsx
  frontend/staff-dashboard/src/pages/discounts/list.tsx
  yarn.lock
Labels: Needs Review, product:mitx-online

#1639 add management command to create local enrollments from edx
  courses/management/commands/create_local_enrollments.py
Labels: Needs Review
