Repository mitodl/mitxonline, pull requests merged in 2023-07, with the labels that each got.

#1719 Update MM grade import, add missing enrollment import script
  micromasters_import/management/commands/queries/008_import_combined_final_grade.sql
  micromasters_import/management/commands/queries/013_add_missing_enrollments_from_certificates.sql
Labels: Needs Review

#1721 Clears discounts when reusing an existing PendingOrder
  ecommerce/models.py
  ecommerce/models_test.py
Labels: Waiting on Author

#1717 Add unverify option to google sheets plugin
  courses/api.py
  sheets/deferrals_plugin.py
Labels: Needs Review

#1724 Added support for featured images in programs
  cms/serializers.py
  courses/serializers.py
  courses/serializers_test.py
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/factories/course.js
  frontend/public/src/flow/courseTypes.js
Labels: needs design, product:mitx-online

#1726 Refund Order should return propper error message
  ecommerce/admin.py
  ecommerce/api.py
  ecommerce/api_test.py
  sheets/refunds_plugin.py
Labels: Needs Review

#1733 Add hubspot_sync celery task queue specifically for hubspot related tasks
  Procfile
  docker-compose.yml
  main/celery.py
  main/settings.py
Labels: Waiting on Author

#1731 1718 improve hubspot bulk update database queries
  hubspot_sync/api.py
  hubspot_sync/api_test.py
  hubspot_sync/management/commands/create_order_from_course_run_enrollments.py
  hubspot_sync/task_helpers.py
  hubspot_sync/tasks.py
  hubspot_sync/tasks_test.py
Labels: Waiting on Author

#1736 Refactors serializers/views for speed in enrollment APIs, adds flag to designate requirements as electives or not
  courses/factories.py
  courses/forms.py
  courses/migrations/0037_update_programrequirements_add_elective_flag.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views/v1/__init__.py
  courses/views_test.py
Labels: Needs Review

#1743 Add hubspot task queue to worker dyno
  Procfile
Labels: Waiting on Author

#1748 Updates the discount redemption cleanup code to be more resilient
  ecommerce/models.py
  ecommerce/models_test.py
Labels: Waiting on Author, product:mitx-online

#1684 feat: remove link and add description for unenrollable runs in more dates
  cms/models.py
  cms/models_test.py
  cms/templates/product_page.html
  frontend/public/scss/product-details.scss
Labels: Waiting on Author

#1746 1740: Re-enroll learner into program
  courses/api.py
  courses/api_test.py
Labels: Needs Review

#1750 ProgramSerializer should now return default image if there's no program page
  courses/serializers.py
  courses/serializers_test.py
  courses/views/v1/__init__.py
Labels: Waiting on Author, product:mitx-online

#1732 add migration to delete duplicate discount redemption
  ecommerce/migrations/0035_delete_duplicate_discountredemption.py
Labels: Waiting on Author

#1754 Populate letter grades for 3T2022
  courses/migrations/0038_populate_letter_grades_3T2022.py
Labels: Needs Review

#1747 No audit grades in program records
  courses/serializers.py
  courses/serializers_test.py
Labels: Waiting on Author

#1751 1694: added stipulations to program electives causes 500 error in Django admin
  courses/forms.py
Labels: Needs Review

#1735 Sheets functionality and usage description
  sheets/README.md
Labels: Needs Review

#1759 Django Admin course validation for Program nested elective operators
  courses/forms.py
Labels: Needs Review

#1765 Ignore ordering in tests where it doesn't matter
  courses/views_test.py
  hubspot_sync/tasks_test.py
Labels: Needs Review

#1760 Updates import_course a bit for program requirements
  courses/management/commands/import_courserun.py
Labels: Waiting on Author

#1775 Program records: show verified grades or grades with certificate
  courses/serializers.py
Labels: Needs Review

#1778 Add program_type field to database
  courses/admin.py
  courses/forms.py
  courses/migrations/0033_populate_letter_grades.py
  courses/migrations/0036_update_letter_grades_for_dedp.py
  courses/migrations/0039_program_program_type.py
  courses/models.py
Labels: Waiting on Author

#1782 Fixing amounts for the default tiers for the configure_tiers command
  flexiblepricing/management/commands/configure_tiers.py
Labels: Waiting on Author, product:mitx-online

#1776 Deferrals better message
  courses/api.py
  sheets/deferrals_plugin.py
Labels: Needs Review

#1786 Migrate instructor data to individual selectable pages
  cms/api.py
  cms/commands_test.py
  cms/constants.py
  cms/factories.py
  cms/management/commands/configure_wagtail.py
  cms/management/commands/convert_faculty_to_pages.py
  cms/migrations/0028_add_instructor_page_models.py
  cms/migrations/0029_add_linked_instructors_to_product_pages.py
  cms/models.py
  cms/models_test.py
  cms/templates/product_page.html
Labels: Waiting on Author, product:mitx-online
