Repository mitodl/mitxonline, pull requests merged in 2023-11, with the labels that each got.

#1971 Change Catalog Page to use the new v2 programs endpoint
  courses/serializers/v2/programs.py
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/flow/cmsTypes.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/queries/courseRuns.js
  frontend/public/src/lib/queries/programs.js
Labels: Needs Review, release blocker, product:mitx-online

#1965 Enrollment dialog WCAG fixes
  frontend/public/scss/common.scss
  frontend/public/scss/layout.scss
  frontend/public/scss/product-details.scss
  frontend/public/scss/product-page/product-details.scss
  frontend/public/scss/variables.scss
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  static/images/certificates/certificate-logo.svg
Labels: Needs Review, product:mitx-online

#1960 Course About Page: tablet and mobile view adjustments
  cms/templates/product_page.html
  frontend/public/scss/product-page/product-details.scss
Labels: Needs Review

#1975 Fixing the mobile styling on the enrollment modal
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: Needs Review, product:mitx-online

#1973 Update how we call the posthog API to include another person identifier to allow for easier targetting
  cms/models.py
  cms/models_test.py
  cms/templates/product_page.html
  frontend/public/src/components/AnonymousMenu.js
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/Header.js
  frontend/public/src/components/ProgramProductDetailEnroll.js
  frontend/public/src/components/UserMenu.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/entry/header.js
  frontend/public/src/lib/util.js
  frontend/public/src/lib/util_test.js
  main/features.py
  main/views.py
Labels: Needs Review, product:mitx-online

#1977 Removing final vestiges of clickable more dates selectors
  frontend/public/src/components/CourseInfoBox.js
Labels: Needs Review

#1969 Update header design and navigation
  frontend/public/scss/top-app-bar.scss
  frontend/public/src/components/AnonymousMenu.js
  frontend/public/src/components/TopBar.js
  frontend/public/src/components/UserMenu.js
Labels: Needs Review

#1979 Fixing date to display if you're logged in
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  frontend/public/src/factories/course.js
Labels: Needs Review, product:mitx-online

#1982 Fix Program Share URLs
  courses/urls/__init__.py
Labels: bug, product:mitx-online

#1983 Adds v2 of the courses API for the program page
  cms/serializers.py
  courses/serializers/v2/courses.py
  courses/urls/v2/urls.py
  courses/views/v2/__init__.py
  courses/views/v2/views_test.py
  flexiblepricing/api.py
Labels: Needs Review, product:mitx-online

#1985 Adding a test for archived courses
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
Labels: Needs Review, product:mitx-online

#1990 Add page__live filter to programs API and update url in catalog page query
  cms/serializers.py
  courses/views/v2/__init__.py
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/lib/queries/programs.js
Labels: Needs Review, product:mitx-online

#1989 Updated v1 course API to only pull live programs; added tests
  courses/serializers/v1/courses.py
  courses/views/v1/views_test.py
Labels: Waiting on Author, product:mitx-online

#1981 Adding breadcrumb navigation and program type badge
  cms/templates/product_page.html
  frontend/public/scss/product-page/product-details.scss
  static/images/breadcrumb-arrow.svg
Labels: Waiting on Author

#1987 Change Catalog to use v2 API endpoint for courses
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/lib/queries/catalogCourses.js
Labels: Needs Review, product:mitx-online

#1988 Header nav links fixes
  frontend/public/src/components/AnonymousMenu.js
  frontend/public/src/components/UserMenu.js
Labels: Needs Review

#1992 Fixes start date formatting in CourseInfoBox, refactors date display for reuse
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/lib/util.js
  frontend/public/src/lib/util_test.js
Labels: Waiting on Author, product:mitx-online

#1996 Product Page: Display none for hidden text
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
Labels: Needs Review

#1995 Headings for required courses start date
  cms/templates/course_list_card.html
  frontend/public/scss/product-page/program-courses.scss
Labels: Needs Review

#1998 Fixes financial assistance form URL for programs that don't have their own
  cms/serializers.py
  cms/serializers_test.py
Labels: Needs Review, product:mitx-online

#2001 Updates the onclick for the instructor name to activate on keyup, fixes an issue with financial assistance page serialization
  cms/serializers.py
  cms/serializers_test.py
  cms/templates/product_page.html
Labels: Waiting on Author, product:mitx-online

#1999 Reoder product info for mobile view
  cms/templates/product_page.html
  frontend/public/scss/product-page/product-details.scss
Labels: Needs Review

#1997 Departments v2 endpoint - now with more course and program counts
  courses/factories.py
  courses/serializers/v2/departments.py
  courses/serializers/v2/departments_test.py
  courses/urls/v2/urls.py
  courses/views/test_utils.py
  courses/views/v2/__init__.py
  courses/views/v2/views_test.py
Labels: Needs Review, product:mitx-online

#2007 Updates CSS to add hover states on the program course cards
  frontend/public/scss/product-page/program-courses.scss
  frontend/public/scss/variables.scss
Labels: Needs Review, product:mitx-online

#2006 Announce course count change
  frontend/public/src/containers/pages/CatalogPage.js
Labels: Needs Review

#2008 Fix just the counts from Catalog
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/queries/catalogCourses.js
  frontend/public/src/lib/queries/departments.js
  frontend/public/src/lib/queries/programs.js
Labels: Needs Review, product:mitx-online

#2005 Catalog Page: updating header and list elements
  frontend/public/scss/catalog.scss
  frontend/public/src/containers/pages/CatalogPage.js
Labels: Needs Review

#2004 Accessibility: Make label visible to screen reader
  frontend/public/scss/home-page/home-page-contact-row.scss
Labels: Needs Review
