Repository mitodl/mitxonline, pull requests merged in 2023-08, with the labels that each got.

#1787 Populate passing DEDP grades that were set to None by Admin
  courses/migrations/0040_populate_none_letter_grades_for_DEDP.py
Labels: Needs Review

#1789 remove assertRaises
  frontend/public/src/lib/util.js
  frontend/public/src/lib/util_test.js
Labels: Waiting on Author

#1766 Use poetry for python dependency management
  .github/workflows/ci.yml
  Dockerfile
  RELEASE.rst
  app.base.json
  app.json
  authentication/middleware_test.py
  poetry.lock
  pyproject.toml
  requirements.in
  requirements.txt
  runtime.txt
  scripts/test/detect_missing_migrations.sh
  scripts/test/python_tests.sh
  test_requirements.txt
Labels: Needs Review

#1800 Instructions for updating python dependencies with poetry
  README.md
Labels: Needs Review

#1807 Fixes per-course instructor page migrations
  cms/management/commands/convert_faculty_to_pages.py
Labels: Waiting on Author

#1761 feat: force all enrollments
  courses/api.py
  courses/api_test.py
  courses/management/commands/create_verified_enrollment.py
  ecommerce/api.py
  ecommerce/api_test.py
  ecommerce/mail_api_test.py
  ecommerce/models_test.py
  ecommerce/serializers_test.py
  ecommerce/tasks_test.py
  ecommerce/views_test.py
  openedx/api.py
  openedx/api_test.py
Labels: Waiting on Author

#1809 Add posthog to repo
  app.json
  frontend/public/package.json
  main/settings.py
  poetry.lock
  pyproject.toml
  yarn.lock
Labels: Waiting on Author

#1814 Adds the PostHog settings to the JS settings so we can use it in React
  main/utils.py
  main/utils_test.py
Labels: Waiting on Author, product:mitx-online

#1812 Updates to prefer long bio over short for existing design
  cms/management/commands/convert_faculty_to_pages.py
  cms/migrations/0030_move_instructor_short_bios_to_long.py
  cms/templates/product_page.html
Labels: Waiting on Author

#1785 feat: add ability to retire users on edX
  app.json
  main/settings.py
  openedx/api.py
  openedx/api_test.py
  poetry.lock
  pyproject.toml
  users/management/commands/retire_users.py
  users/management/tests/retire_users_test.py
  users/management/tests/unblock_users_test.py
Labels: Waiting on Author

#1823 Update to Enrolled in certificate track label to count for audit enrollment with certificates
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#1790 When deferring enrollment set to verified
  courses/api.py
  courses/api_test.py
Labels: Waiting on Author

#1825 update full name on user profile
  hubspot_sync/api.py
  users/serializers.py
  users/views.py
Labels: Waiting on Author

#1820 Featured Products Carousel
  cms/api_test.py
  cms/migrations/0032_alter_homeproductlink_course_product_page.py
  cms/models.py
  cms/templates/home_page.html
  frontend/public/scss/featured-product-cards.scss
  frontend/public/scss/variables.scss
  frontend/public/src/entry/style.js
  frontend/public/src/lib/util.js
  static/images/featured-product-rectangle.svg
  static/images/featured-products-left-arrow.svg
  static/images/featured-products-right-arrow.svg
Labels: Needs Review

#1830 Fixes text alignment for the Enrolled button, hide the upsell card in new design
  frontend/public/scss/meta-product-page.scss
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/containers/UpsellCardApp.js
Labels: Needs Review, product:mitx-online

#1818 1676 design new catalog page
  .env.example
  courses/README.md
  courses/admin.py
  courses/forms.py
  courses/migrations/0041_rename_topics_add_to_programs.py
  courses/migrations/0042_add_ordering_to_course_and_program.py
  courses/models.py
  courses/models_test.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views/v1/__init__.py
  courses/views_test.py
  frontend/public/scss/catalog.scss
  frontend/public/scss/layout.scss
  frontend/public/src/containers/App.js
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/factories/course.js
  frontend/public/src/flow/courseTypes.js
  frontend/public/src/lib/queries/courses.js
  frontend/public/src/lib/queries/programs.js
  frontend/public/src/lib/urls.js
  main/urls.py
  main/views.py
  main/views_test.py
  static/images/filter_list_alt.svg
Labels: Needs Review

#1832 New extended certificate generation window
  app.json
  courses/api.py
  courses/api_test.py
  main/settings.py
Labels: Needs Review

#1826 Home Page Hero Component
  cms/models.py
  cms/templates/home_page.html
  frontend/public/scss/home-page-hero.scss
  frontend/public/src/entry/style.js
  static/images/home-page-hero-image.png
Labels: Needs Review

#1841 Anonymous user handling for posthog
  cms/models.py
Labels: Waiting on Author

#1840 Fix background css on feature flagged areas
  cms/templates/home_page.html
  cms/templates/product_page.html
  frontend/public/scss/home-page/home-page-hero.scss
  frontend/public/scss/meta-product-page.scss
Labels: Needs Review

#1792 Make hashed webpack output filenames more stable
  frontend/public/webpack.config.js
Labels: Needs Review
