Repository mitodl/mitxonline, pull requests merged in 2023-09, with the labels that each got.

#1846 1842: duplicate ProductPage get_context method in model
  cms/models.py
Labels: Waiting on Author

#1847 1845: Remove unused feature flag and import
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/forms/EditProfileForm.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/containers/pages/register/RegisterDetailsPage.js
  frontend/public/src/flow/declarations.js
  main/features.py
  main/utils.py
  main/utils_test.py
Labels: Needs Review

#1861 fix expandable Read More 500 error
  cms/templatetags/expand.py
Labels: Needs Review

#1848 fix profile validation and regex error
  frontend/public/src/components/forms/ProfileFormFields.js
Labels: Waiting on Author

#1863 Home Page New Hero Background Fix
  cms/templates/home_page.html
  frontend/public/scss/home-page/home-page-hero.scss
  frontend/public/scss/variables.scss
Labels: Waiting on Author

#1853 Home Page Contact Component
  .env.example
  app.json
  cms/models.py
  cms/templates/home_page.html
  frontend/public/scss/home-page/home-page-contact-row.scss
  frontend/public/scss/layout.scss
  frontend/public/scss/meta-product-page.scss
  frontend/public/scss/variables.scss
  main/features.py
  main/settings.py
Labels: Waiting on Author

#1716 remove non-standard issue templates
  .github/ISSUE_TEMPLATE/bug_template.md
  .github/ISSUE_TEMPLATE/config_change_template.md
  .github/ISSUE_TEMPLATE/feature_template.md
Labels: Needs Review

#1866 Change fonts to new correct fonts for home page
  cms/templates/home_page.html
  frontend/public/scss/home-page/featured-product-cards.scss
  frontend/public/scss/home-page/home-page-contact-row.scss
  frontend/public/scss/home-page/home-page-hero.scss
  frontend/public/scss/home-page/home-page-video-component.scss
  main/templates/base.html
Labels: Needs Review, product:mitx-online

#1871 1870: Remove duplicate catalog URL path
  main/urls.py
Labels: Needs Review

#1872 1869: Course program api performance improvements
  cms/models.py
  cms/serializers.py
  courses/api.py
  courses/migrations/0043_course_program_live_index.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views/v1/__init__.py
  courses/views_test.py
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/factories/course.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
  frontend/public/src/lib/queries/courseRuns.js
  frontend/public/src/lib/queries/courses.js
  frontend/public/src/lib/queries/programs.js
Labels: Needs Review

#1877 Department REST API
  courses/serializers.py
  courses/urls.py
  courses/views/v1/__init__.py
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/lib/queries/departments.js
Labels: Needs Review

#1881 New design footer css updates
  frontend/public/scss/footer.scss
Labels: Needs Review

#1885 Repair cart page including reinstated course api improvements
  cms/models.py
  cms/serializers.py
  courses/api.py
  courses/migrations/0043_course_program_live_index.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  courses/urls.py
  courses/views/v1/__init__.py
  courses/views_test.py
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/ProductDetailEnrollApp_test.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/containers/pages/checkout/CartPage.js
  frontend/public/src/factories/course.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
  frontend/public/src/lib/queries/courseRuns.js
  frontend/public/src/lib/queries/courses.js
  frontend/public/src/lib/queries/departments.js
  frontend/public/src/lib/queries/programs.js
Labels: Needs Review

#1883 Updating video player CSS to work better in the new design
  cms/templates/product_page.html
  cms/templates/videojs_tag.html
  cms/templatetags/videojs.py
  frontend/public/scss/product-page/product-details.scss
Labels: Needs Review, product:mitx-online

#1888 Use site name variable (MITx Online) for page title
  main/templates/index.html
Labels: Needs Review

#1878 Course passed if has course run certificate
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/lib/courseApi.js
Labels: Waiting on Author

#1875 Video Component Styling fix
  cms/templates/home_page.html
  frontend/public/scss/home-page/home-page-contact-row.scss
  frontend/public/scss/home-page/home-page-video-component.scss
Labels: Waiting on Author, product:mitx-online

#1889 Fixes to Featured Carousel
  cms/templates/home_page.html
  frontend/public/scss/home-page/featured-product-cards.scss
  frontend/public/scss/home-page/home-page-hero.scss
  main/templates/partials/featured_product_card.html
Labels: Needs Review, product:mitx-online

#1887 Updates create_courseware to allow you to specify departments (optionally creating them)
  courses/management/commands/create_courseware.py
Labels: Waiting on Author, product:mitx-online

#1890 footer css updates for mobile landscape screen
  frontend/public/scss/footer.scss
Labels: Needs Review

#1897 Hero sits over dropdown because of carousel z index change
  frontend/public/scss/home-page/home-page-hero.scss
Labels: Waiting on Author, product:mitx-online

#1892 Add courses api filters to catalog page
  courses/migrations/0044_alter_courserun_live.py
  courses/models.py
  courses/views/v1/__init__.py
  frontend/public/src/containers/pages/CatalogPage_test.js
  frontend/public/src/lib/queries/courses.js
Labels: Waiting on Author

#1900 Updates the code behind the More Dates selector to work without the course page
  frontend/public/src/containers/ProductDetailEnrollApp.js
Labels: Waiting on Author, product:mitx-online

#1904 Swap posthog to use js sdk with minimal settings
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/lib/util.js
Labels: Needs Review

#1899 User dropdown menu updates
  frontend/public/scss/top-app-bar.scss
  frontend/public/scss/user-menu.scss
  frontend/public/src/components/UserMenu.js
Labels: Waiting on Author

#1833 New design: adds program page
  cms/models.py
  cms/serializers.py
  cms/templates/course_list_card.html
  cms/templates/product_page.html
  cms/templatetags/course_list.py
  courses/api.py
  courses/models.py
  courses/views/v1/__init__.py
  frontend/public/scss/layout.scss
  frontend/public/scss/product-details.scss
  frontend/public/scss/product-page/product-details.scss
  frontend/public/scss/product-page/program-courses.scss
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  frontend/public/src/components/ProgramInfoBox.js
  frontend/public/src/components/ProgramProductDetailEnroll.js
  frontend/public/src/components/ProgramProductDetailEnroll_test.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/entry/header.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/queries/courseRuns.js
  frontend/public/src/lib/util.js
  static/images/products/browser.png
Labels: Waiting on Author, product:mitx-online

#1891 Catalog page css updates - v1
  frontend/public/scss/catalog.scss
  frontend/public/src/containers/pages/CatalogPage.js
Labels: Needs Review

#1909 Re-add the fix from PR 1900 to the reworked product page components
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: Needs Review, product:mitx-online

#1907 Skip courses if they don't have a published CMS page
  cms/templatetags/course_list.py
Labels: Waiting on Author, product:mitx-online

#1911 Self paced dates -> start any time
  cms/api_test.py
  cms/models.py
  main/templates/partials/featured_product_card.html
Labels: Needs Review, product:mitx-online

#1917 Add FAQ cert link and prerequisites to product_page.html
  cms/templates/product_page.html
  frontend/public/src/components/CourseInfoBox.js
Labels: Needs Review, product:mitx-online

#1920 Fix Duplicate Courses on Catalog Page
  courses/views/v1/__init__.py
Labels: Needs Review, product:mitx-online

#1921 Course Calatog: Stay on selected department
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
Labels: Needs Review

#1923 Update course info bar to respond to archived courses
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/components/CourseInfoBox.js
  main/templates/base.html
Labels: Needs Review, product:mitx-online

#1903 Assorted fixes for More Dates selector in existing design
  cms/models.py
  cms/templates/product_page.html
  courses/api.py
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: product:mitx-online

#1927 Update the Certificate field for archived courses
  frontend/public/src/components/CourseInfoBox.js
Labels: Needs Review, product:mitx-online
