Repository mitodl/mitxonline, pull requests merged in 2023-06, with the labels that each got.

#1645 Updates the email address on the frontend to use the value from settings
  frontend/public/scss/receipt.scss
  frontend/public/src/components/ReceiptPageDetailCard.js
Labels: Waiting on Author, product:mitx-online

#1641 Make deferral functionality atomic and clarify errors
  courses/api.py
  courses/api_test.py
  courses/management/commands/defer_enrollment.py
  courses/management/utils_test.py
Labels: Waiting on Author

#1650 Adds validation for edX profile fields
  openedx/api.py
  users/models.py
  users/models_test.py
Labels: Waiting on Author, product:mitx-online

#1653 703: navigation drawer component not screen reader accessible round 2
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
Labels: Needs Review

#1655 Updating refund_order API to check for PayPal
  ecommerce/api.py
  ecommerce/api_test.py
Labels: Needs Review

#1644 904: tracking audit enrollments for mitx online courses in hubspot
  courses/api.py
  courses/api_test.py
  courses/management/commands/test_unenroll_enrollment.py
  courses/serializers.py
  courses/views/v1/__init__.py
  courses/views_test.py
  ecommerce/api.py
  ecommerce/models.py
  ecommerce/models_test.py
  hubspot_sync/api_test.py
  hubspot_sync/conftest.py
  hubspot_sync/management/commands/configure_hubspot_properties.py
  hubspot_sync/serializers.py
  hubspot_sync/serializers_test.py
Labels: Needs Review

#1663 Handle un-enrollment prior to audit enrollment Order creation feature
  courses/api.py
  courses/api_test.py
  courses/management/commands/test_unenroll_enrollment.py
  ecommerce/factories.py
Labels: Waiting on Author

#1667 Handle HubSpot exceptions when unenrolling from a course
  courses/api.py
  courses/api_test.py
  courses/management/commands/test_unenroll_enrollment.py
  hubspot_sync/task_helpers.py
  hubspot_sync/tasks.py
Labels: Waiting on Author

#1672 Adding date checks to Discount model
  ecommerce/models.py
  ecommerce/models_test.py
  ecommerce/views_test.py
  flexiblepricing/api_test.py
  requirements.txt
  test_requirements.txt
Labels: Waiting on Author

#1676 Update google-sheets-refunds/deferrals
  requirements.in
  requirements.txt
Labels: Needs Review

#1674 1664: management command to create Order from enrollment
  courses/views/v1/__init__.py
  ecommerce/api.py
  ecommerce/management/commands/refund_fulfilled_order.py
  ecommerce/models.py
  ecommerce/models_test.py
  hubspot_sync/management/commands/create_order_from_course_run_enrollments.py
Labels: Waiting on Author

#1651 Convert grade into letter for program records
  courses/migrations/0031_populate_letter_grades.py
  courses/utils.py
Labels: Needs Review

#1687 fix bug on renderCourseInfoCard and add migration to backfill certificate enrollments
  courses/migrations/0031_backfill_enrollments_from_certificates.py
  frontend/public/src/components/ProgramEnrollmentDrawer.js
Labels: Needs Review

#1704 fix courses migration conflict
  courses/migrations/0031_populate_letter_grades.py
  courses/migrations/0033_populate_letter_grades.py
  courses/migrations/0034_backfill_enrollments_from_certificates.py
  courses/utils.py
Labels: Needs Review

#1708 Optimize program enrollments API
  courses/migrations/0033_add_related_name_to_program_enrollments.py
  courses/models.py
  courses/serializers.py
  courses/serializers_test.py
  courses/views/v1/__init__.py
  courses/views_test.py
Labels: Waiting on Author

#1709 Merging migrations from #1708 and #1704
  courses/migrations/0035_merge_related_name_and_backfill_enrollments.py
Labels: Needs Review, product:mitx-online

#1707 1691: program certificate generation does not adhere to nested program electives
  courses/api.py
  courses/api_test.py
  courses/management/commands/test_manage_program_certificate.py
Labels: Needs Review

#1703 1702: line serializer cannot handle orders with no current enrollment
  hubspot_sync/api_test.py
  hubspot_sync/serializers.py
  hubspot_sync/serializers_test.py
Labels: Needs Review

#1706 Refund Order: remove atomicity and rollback
  ecommerce/api.py
Labels: Needs Review
