Repository mitodl/mitxonline, pull requests merged in 2023-10, with the labels that each got.

#1937 Revert "Assorted fixes for More Dates selector in existing design"
  cms/models.py
  cms/templates/product_page.html
  courses/api.py
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: Needs Review, product:mitx-online

#1931 don't leak grades in program record before course completed
  courses/serializers.py
  courses/serializers_test.py
Labels: Needs Review

#1941 Catalog Page: Add content loader
  frontend/public/src/components/CourseLoader.js
  frontend/public/src/containers/pages/CatalogPage.js
  package.json
  yarn.lock
Labels: Needs Review

#1942 Course About Redesign - Accessibility issues on instructor bio
  cms/templates/product_page.html
Labels: Needs Review

#1938 Remove start date from ProgramInfoBox.js
  frontend/public/src/components/ProgramInfoBox.js
Labels: Waiting on Author, product:mitx-online

#1945 Product Page: Fix overflow on faculty info boxes
  frontend/public/scss/product-faculty-members.scss
Labels: Needs Review

#1951 Course Page: More enrollment dates updates
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: Needs Review

#1949 Product Page: about section Show More toggle updates
  cms/templatetags/expand.py
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
Labels: Needs Review

#1954 Filter out not live programs
  courses/api.py
Labels: Needs Review

#1956 Catalog Page: Mobile view changes
  frontend/public/scss/catalog.scss
  frontend/public/scss/top-app-bar.scss
  frontend/public/src/components/UserMenu.js
  frontend/public/src/containers/pages/CatalogPage.js
Labels: Needs Review

#1957 Course About Page: update font and styles
  frontend/public/scss/product-page/product-details.scss
  frontend/public/scss/top-app-bar.scss
  frontend/public/src/components/CourseInfoBox.js
  main/templates/base.html
Labels: Needs Review

#1962 Course API test updates
  courses/conftest.py
  courses/views/v1/__init__.py
  courses/views_test.py
  fixtures/common.py
  main/test_utils.py
  poetry.lock
  pyproject.toml
Labels: Waiting on Author, release blocker, product:mitx-online

#1961 Instructor popup modal mobile view
  cms/templates/product_page.html
  frontend/public/scss/product-page/product-details.scss
Labels: Needs Review

#1963 Program API test updates
  courses/views_test.py
Labels: Needs Review, release blocker, product:mitx-online

#1940 Updated get_financial_assistance_form_url to also consider related programs
  cms/serializers.py
  cms/serializers_test.py
  courses/models.py
Labels: Needs Review, product:mitx-online

#1967 New design for the instructor bio cards on the course about page
  frontend/public/scss/product-faculty-members.scss
  frontend/public/scss/product-page/product-details.scss
Labels: Needs Review
