Repository mitodl/mitxonline, pull requests merged in 2024-01, with the labels that each got.

#2044 Check to make sure the end date and upgrade deadline haven't passed before grabbing your audit enrollment
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
Labels: Needs Review, product:mitx-online

#2046 When resolving the current run, make sure it's also enrollable
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: Waiting on Author, product:mitx-online

#2048 display course number on program enroll modal
  frontend/public/src/components/ProgramProductDetailEnroll.js
Labels: Waiting on Author

#2050 add next parameter to course and program enrollment pages for unauthenticated users
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/ProgramProductDetailEnroll.js
Labels: Needs Review

#2043 Remove role menu
  frontend/public/src/components/UserMenu.js
Labels: Needs Review

#2053 Add css in for visual focus on modal buttons
  frontend/public/scss/product-page/product-details.scss
Labels: Needs Review

#2057 create_courseware command no department defined error
  courses/management/commands/create_courseware.py
Labels: Needs Review

#2054 Explain Course Formats
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/ProgramInfoBox.js
Labels: On Hold, blocked

#2063 Show More link on product about page accessibility
  cms/templatetags/expand.py
Labels: Needs Review

#2062 3362: No opacity on program card, pointer when hovering
  cms/templates/course_list_card.html
  frontend/public/scss/product-page/program-courses.scss
Labels: Needs Review

#2059 Delay alert when rendering the page in order to engage screen reader alert
  frontend/public/src/components/NotificationContainer.js
  frontend/public/src/components/TopBar.js
Labels: Needs Review

#2064 Removes instances where we've feature flagged the new (current) design
  cms/templates/product_page.html
  frontend/public/src/components/AnonymousMenu.js
  frontend/public/src/components/AnonymousMenu_test.js
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/Header.js
  frontend/public/src/components/ProgramProductDetailEnroll.js
  frontend/public/src/components/TopAppBar.js
  frontend/public/src/components/TopAppBar_test.js
  frontend/public/src/components/UserMenu.js
  frontend/public/src/components/UserMenu_test.js
  frontend/public/src/components/forms/EditProfileForm_test.js
  frontend/public/src/containers/ProductDetailEnrollApp.js
  frontend/public/src/containers/UpsellCardApp.js
  frontend/public/src/entry/header.js
  main/urls.py
  main/views.py
  main/views_test.py
Labels: Waiting on Author, product:mitx-online

#2065 3400 remove enrolled state and modal default
  courses/views/v1/__init__.py
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
Labels: Needs Review

#2066 3382: self paced courses with future start dates show start anytime
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/lib/util.js
  frontend/public/src/lib/util_test.js
Labels: Needs Review

#2061 Fix program id retrieval when sharing
  frontend/public/src/containers/pages/records/LearnerRecordsPage.js
Labels: Waiting on Author

#2069 Updated fixed price test to be less flaky
  ecommerce/models_test.py
Labels: Needs Review, product:mitx-online

#2070 Update Publish Documentation to newer versions of stuff so it runs
  .github/workflows/docs.yml
  pants-plugins/mitol/docs/register.py
  pants.toml
Labels: Needs Review, product:mitx-online

#2071 Catalog: sorting courses and programs by title
  courses/views/v2/__init__.py
Labels: Needs Review

#2073 Wrapping product creation in a create_version block so versions happen like they should
  courses/views/v2/views_test.py
  ecommerce/management/commands/create_product.py
Labels: Waiting on Author, product:mitx-online
