Repository mitodl/mitxonline, pull requests merged in 2024-03, with the labels that each got.

#2117 adding enrollment change tracking
  courses/admin.py
  courses/migrations/0045_audit_modified_by.py
  courses/migrations/0046_audit_rename_call_stack.py
  ecommerce/management/commands/refund_fulfilled_order.py
  main/models.py
  main/utils_test.py
Labels: Needs Review

#2121 Change program end date to certificate creation date
  courses/models.py
  courses/models_test.py
Labels: Needs Review

#2125 2846 Course About: Replace Free with Free to Learn
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/ProgramInfoBox.js
Labels: Waiting on Author

#2127 3360: on account registration redirect new users to the page they started on
  frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
  frontend/public/src/containers/pages/register/RegisterDetailsPage.js
  frontend/public/src/lib/queries/auth.js
Labels: Waiting on Author

#2128 1257: updating meta tags on mitx online site
  cms/migrations/0034_add_search_image_to_course_and_program_page.py
  cms/models.py
  cms/templates/product_page.html
  poetry.lock
  pyproject.toml
Labels: Waiting on Author

#2131 remove extraneous console.log statement
  frontend/public/src/containers/pages/CatalogPage.js
Labels: Needs Review

#2119 Updates to ancillary pages
  cms/templates/flexiblepricing/flexible_pricing_request_form.html
  frontend/public/scss/auth.scss
  frontend/public/scss/cards.scss
  frontend/public/scss/cart.scss
  frontend/public/scss/dashboard.scss
  frontend/public/scss/layout.scss
  frontend/public/scss/learner-records.scss
  frontend/public/scss/order-history.scss
  frontend/public/scss/product-page/product-details.scss
  frontend/public/scss/variables.scss
  frontend/public/src/components/CartItemCard.js
  frontend/public/src/components/EnrolledCourseList.js
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/GetCertificateButton.js
  frontend/public/src/components/OrderSummaryCard.js
  frontend/public/src/components/forms/AddlProfileFieldsForm.js
  frontend/public/src/components/forms/ApplyCouponForm.js
  frontend/public/src/components/forms/ChangeEmailForm.js
  frontend/public/src/components/forms/ChangePasswordForm.js
  frontend/public/src/components/forms/EditProfileForm.js
  frontend/public/src/components/forms/EmailForm.js
  frontend/public/src/components/forms/EmailForm_test.js
  frontend/public/src/components/forms/LoginPasswordForm.js
  frontend/public/src/components/forms/ProfileFormFields.js
  frontend/public/src/components/forms/RegisterDetailsForm.js
  frontend/public/src/components/forms/RegisterEmailForm.js
  frontend/public/src/components/forms/ResetPasswordForm.js
  frontend/public/src/components/input/CardLabel.js
  frontend/public/src/constants.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/containers/pages/checkout/CartPage.js
  frontend/public/src/containers/pages/checkout/OrderHistory.js
  frontend/public/src/containers/pages/login/LoginEmailPage.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordConfirmPage.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordPage.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordPage_test.js
  frontend/public/src/containers/pages/login/LoginPasswordPage.js
  frontend/public/src/containers/pages/profile/EditProfilePage.js
  frontend/public/src/containers/pages/records/LearnerRecordsPage.js
  frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
  frontend/public/src/containers/pages/register/RegisterConfirmPage.js
  frontend/public/src/containers/pages/register/RegisterConfirmPage_test.js
  frontend/public/src/containers/pages/register/RegisterConfirmSentPage.js
  frontend/public/src/containers/pages/register/RegisterConfirmSentPage_test.js
  frontend/public/src/containers/pages/register/RegisterDetailsPage.js
  frontend/public/src/containers/pages/register/RegisterEmailPage.js
  frontend/public/src/containers/pages/settings/AccountSettingsPage.js
  frontend/public/src/containers/pages/settings/EmailConfirmPage.js
  frontend/public/src/containers/pages/settings/EmailConfirmPage_test.js
  frontend/public/src/lib/courseApi.js
  main/settings.py
  main/templates/footer.html
  main/urls.py
  static/images/checkbox-checked.svg
Labels: Waiting on Author, product:mitx-online

#2124 Upgrade dialog choose any course run
  frontend/public/scss/product-details.scss
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
Labels: Needs Review

#2142 Distinguish change forms in account settings
  frontend/public/src/components/forms/ChangeEmailForm.js
  frontend/public/src/components/forms/ChangePasswordForm.js
Labels: Needs Review

#2139 Showing Course rather than Courses (or program/s) when there is only 1 to display
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/CatalogPage_test.js
Labels: Waiting on Author, product:mitx-online

#2141 Upgrade enrollment dialog fixes
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
Labels: Waiting on Author

#2132 3649 all mitxonline courses should have a department
  courses/management/commands/create_courseware.py
  courses/management/commands/import_courserun.py
  courses/migrations/0047_courses_and_programs_department_required.py
  courses/models.py
  docker-compose.yml
  docs/source/commands/configure_instance.rst
  docs/source/commands/configure_tiers.rst
  docs/source/commands/create_courseware.rst
  docs/source/commands/import_courserun.rst
  docs/source/configuration/tutor.rst
  ecommerce/views_test.py
  flexiblepricing/management/commands/configure_tiers.py
  flexiblepricing/management/commands/configure_tiers_test.py
  main/management/commands/configure_instance.py
Labels: Needs Review, blocked

#2144 3005: adding a banner snippet in the header that appears on every page of the site
  cms/migrations/0035_sitebanner.py
  cms/models.py
  frontend/public/scss/banner.scss
  frontend/public/scss/layout.scss
  frontend/public/src/banner.js
  frontend/public/src/entry/django.js
  main/templates/base.html
  main/templates/partials/banner.html
  main/templates/partials/notifications.html
  main/templatetags/banner.py
Labels: Needs Review
