Repository mitodl/mitxonline, pull requests merged in 2024-02, with the labels that each got.

#2077 Fixes use of "redemption_type" when generating discount codes in bulk
  courses/views/v2/views_test.py
  ecommerce/api.py
  ecommerce/views_test.py
Labels: Needs Review, product:mitx-online

#2079 2075: some dialogs email settings unenroll not keyboard navigable
  frontend/public/src/components/EnrolledItemCard.js
Labels: Waiting on Author

#2081 Fix for program unenrollment modal
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#2074 New MITxOnline Logo
  frontend/public/scss/certificates/certificate.scss
  frontend/public/scss/footer.scss
  frontend/public/scss/learner-records.scss
  frontend/public/scss/top-app-bar.scss
  frontend/public/src/components/InstituteLogo.js
  frontend/public/src/components/InstituteLogo_test.js
  frontend/public/src/components/TopBar.js
  main/templates/footer.html
  static/images/mitx-online-logo.png
  static/images/open-learning-logo.png
Labels: Needs Review

#2095 Program courses cards styles
  frontend/public/scss/product-page/program-courses.scss
Labels: Needs Review

#2097 Updating favicon
  static/images/favicon.ico
Labels: Waiting on Author

#2096 Program certificate for different program types
  cms/models.py
  cms/templates/certificate_page.html
Labels: Waiting on Author

#2101 Accessibility: updating intructors info
  cms/templates/product_page.html
  frontend/public/scss/product-faculty-members.scss
  frontend/public/src/containers/ProductDetailEnrollApp.js
Labels: Needs Review

#2103 Admin improvements to CourseRunEnrollmentAudit model
  courses/admin.py
Labels: Needs Review

#2105 fix course card not keyboard accessible issue
  cms/templates/course_list_card.html
  frontend/public/scss/product-page/program-courses.scss
Labels: Needs Review

#2108 Create certs only for live programs
  courses/signals.py
  courses/signals_test.py
Labels: Needs Review

#2110 Certificate Page: End date should be certificate creation date
  courses/models.py
  courses/models_test.py
Labels: Waiting on Author
