Repository mitodl/mitxonline, pull requests merged in 2024-07, with the labels that each got.

#2267 4495 mitx online consolidate abandoned and duplicate css styling
  ecommerce/templates/checkout_interstitial.html
  frontend/public/scss/auth.scss
  frontend/public/scss/certificates/certificate.scss
  frontend/public/scss/common.scss
  frontend/public/scss/footer.scss
  frontend/public/scss/layout.scss
  frontend/public/scss/product-details.scss
  frontend/public/scss/product-faculty-members.scss
  frontend/public/scss/product-page/product-details.scss
  frontend/public/scss/product-page/product-faculty-members.scss
  frontend/public/scss/top-app-bar.scss
  frontend/public/scss/user-menu.scss
  frontend/public/scss/variables.scss
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  frontend/public/src/components/Markdown.js
  frontend/public/src/components/Markdown_test.js
Labels: Needs Review

#2276 Update mitol-django-google-sheets
  app.json
  poetry.lock
  pyproject.toml
Labels: Needs Review

#2275 Clean up constants
  .secrets.baseline
  frontend/public/src/constants.js
  frontend/public/src/containers/pages/profile/EditProfilePage.js
Labels: Needs Review, Waiting on Author

#2279 Login button should indicate when course is archived
  frontend/public/src/components/CourseProductDetailEnroll.js
Labels: Waiting on Author

#2280 4548 dashboard dont display course detail link when the course about page is not published
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
Labels: Needs Review

#2284 Preliminary Test-More-Dates "No Sessions" design: Exclamation point icon - low contrast and spacing
  frontend/public/scss/product-page/product-details.scss
  frontend/public/src/components/CourseInfoBox.js
Labels: Needs Review

#2282 Update eslint-config and friends
  frontend/public/.eslintrc
  frontend/public/package.json
  frontend/public/src/components/CartItemCard.js
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  frontend/public/src/components/EnrolledCourseList_test.js
  frontend/public/src/components/EnrolledItemCard.js
  frontend/public/src/components/EnrolledItemCard_test.js
  frontend/public/src/components/EnrolledProgramList.js
  frontend/public/src/components/OrderSummaryCard.js
  frontend/public/src/components/ProgramCourseInfoCard.js
  frontend/public/src/components/ProgramEnrollmentDrawer.js
  frontend/public/src/components/ProgramInfoBox.js
  frontend/public/src/components/ProgramProductDetailEnroll.js
  frontend/public/src/components/ProgramProductDetailEnroll_test.js
  frontend/public/src/components/ReceiptPageDetailCard.js
  frontend/public/src/components/ScaledRecaptcha.js
  frontend/public/src/components/UserMenu.js
  frontend/public/src/components/forms/AddlProfileFieldsForm.js
  frontend/public/src/components/forms/ChangeEmailForm.js
  frontend/public/src/components/forms/ChangePasswordForm.js
  frontend/public/src/components/forms/EditProfileForm.js
  frontend/public/src/components/forms/ProfileFormFields.js
  frontend/public/src/components/forms/RegisterEmailForm.js
  frontend/public/src/components/forms/ResetPasswordForm.js
  frontend/public/src/containers/pages/CatalogPage.js
  frontend/public/src/containers/pages/DashboardPage.js
  frontend/public/src/containers/pages/checkout/CartPage.js
  frontend/public/src/containers/pages/checkout/OrderHistory.js
  frontend/public/src/containers/pages/checkout/OrderReceiptPage.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordConfirmPage.js
  frontend/public/src/containers/pages/login/LoginForgotPasswordPage.js
  frontend/public/src/containers/pages/records/LearnerRecordsPage.js
  frontend/public/src/containers/pages/register/RegisterConfirmPage.js
  frontend/public/src/containers/pages/register/RegisterConfirmPage_test.js
  frontend/public/src/containers/pages/register/RegisterConfirmSentPage_test.js
  frontend/public/src/containers/pages/register/RegisterDeniedPage_test.js
  frontend/public/src/containers/pages/settings/EmailConfirmPage.js
  frontend/public/src/containers/pages/settings/EmailConfirmPage_test.js
  frontend/public/src/entry/django.js
  frontend/public/src/factories/course.js
  frontend/public/src/lib/auth.js
  frontend/public/src/lib/courseApi.js
  frontend/public/src/lib/courseApi_test.js
  frontend/public/src/lib/notificationsApi.js
  frontend/public/src/lib/queries/catalogCourses.js
  frontend/public/src/lib/queries/courses.js
  frontend/public/src/lib/queries/enrollment.js
  frontend/public/src/lib/sanctuary.js
  frontend/public/src/lib/selectors.js
  frontend/public/src/lib/test_utils.js
  frontend/public/src/lib/util.js
  frontend/public/src/lib/util_test.js
  frontend/public/src/lib/validation.js
  frontend/public/src/store/configureStore.js
  frontend/public/src/util/integration_test_helper.js
  yarn.lock
Labels: Waiting on Author

#2285 Clarify enrollable run
  cms/models.py
  cms/models_test.py
  courses/api.py
  courses/api_test.py
  courses/models.py
  courses/models_test.py
  courses/serializers/v2/departments.py
  courses/utils.py
Labels: Waiting on Author

#2299 Enrollment in a course run without a course page crashes the dashboard
  frontend/public/src/components/EnrolledItemCard.js
Labels: Needs Review

#2305 Show only enrollable runs in the enrollment dialog
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  frontend/public/src/lib/courseApi.js
Labels: Waiting on Author

#2313 Fixing discount code payload generation for Google Analytics
  ecommerce/views/v0/__init__.py
Labels: Needs Review, product:mitx-online

#2304 Info box slow render fixes
  cms/models.py
  cms/models_test.py
  cms/templates/product_page.html
  courses/api.py
  courses/api_test.py
  courses/serializers/base.py
  frontend/public/src/components/CourseInfoBox.js
  frontend/public/src/components/CourseProductDetailEnroll.js
  frontend/public/src/components/CourseProductDetailEnroll_test.js
  frontend/public/src/components/ProgramProductDetailEnroll.js
Labels: Needs Review

#2300 When creating enrollment set is_active explicitly in the enrollment api call
  openedx/api.py
  openedx/api_test.py
Labels: Waiting on Author
