Repository mitodl/mitxonline, pull requests merged in 2025-05, with the labels that each got.

#2620 Make gemini optional on PRs
  .gemini/config.yaml
  .gemini/styleguide.md
Labels: Needs Review

#2637 add v1 and v2 to the openapi spec
  main/settings.py
  openapi/specs/v1.yaml
  openapi/specs/v2.yaml
Labels: Needs Review

#2635 Update the extra hosts section to include local.openedx.io
  docker-compose.yml
Labels: Waiting on Author, product:mitx-online

#2610 Add B2B organizations
  b2b/__init__.py
  b2b/api.py
  b2b/api_test.py
  b2b/apps.py
  b2b/constants.py
  b2b/factories.py
  b2b/management/__init__.py
  b2b/management/commands/__init__.py
  b2b/management/commands/b2b_contract.py
  b2b/management/commands/b2b_list.py
  b2b/migrations/0001_add_orgs_and_contracts_models.py
  b2b/migrations/__init__.py
  b2b/models.py
  b2b/serializers/__init__.py
  b2b/serializers/v0/__init__.py
  b2b/urls.py
  b2b/views/__init__.py
  b2b/views/v0/__init__.py
  b2b/views/v0/urls.py
  cms/commands_test.py
  cms/management/commands/configure_wagtail.py
  courses/api.py
  courses/migrations/0061_add_b2b_contract_link_to_courseruns.py
  courses/models.py
  main/settings.py
  main/urls.py
  main/utils.py
  main/utils_test.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  openapi/specs/v2.yaml
  poetry.lock
  pyproject.toml
  users/constants.py
Labels: Needs Review

#2640 Remove the 0028 migration that sets usernames to email addresses
  users/migrations/0028_set_username_to_email.py
Labels: Needs Review, product:mitx-online

#2643 Add management command to copy email into username field
  users/constants.py
  users/management/commands/migrate_usernames.py
  users/management/tests/migrate_usernames_test.py
Labels: Needs Review

#2649 Adding OTEL metric shipping to mitxonline
  app.json
  main/apps.py
  main/settings.py
  main/telemetry.py
  poetry.lock
  pyproject.toml
Labels: enhancement, DevOps

#2650 Create profile and legal address on apisix auth
  main/settings.py
Labels: Needs Review

#2658 Update edx user profile asynchronously
  users/views.py
Labels: Needs Review

#2659 Update Users API to be versioned (at v0), so it shows up in the OpenAPI spec
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  openapi/specs/v2.yaml
  users/serializers.py
  users/urls.py
Labels: Needs Review

#2660 Add API key for B2B data
  b2b/management/commands/b2b_list.py
  b2b/models.py
  b2b/views/v0/__init__.py
  main/settings.py
  poetry.lock
  pyproject.toml
  users/models.py
Labels: Needs Review

#2654 B2B Provisioning: Create enrollment codes when contracts are in place
  b2b/api.py
  b2b/api_test.py
  b2b/management/commands/b2b_contract.py
  b2b/management/commands/b2b_list.py
  b2b/migrations/0002_add_max_learners_price_fields_to_contract.py
  b2b/models.py
  b2b/tasks.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  openapi/specs/v2.yaml
Labels: Needs Review

#2666 Add missing ALLOWED_REDIRECT_HOSTS variable
  app.json
  main/settings.py
Labels: Needs Review

#2667 Remove configure hubspot command
  courses/signals.py
  courses/signals_test.py
Labels: Needs Review

#2669 Rename the realm import file
  config/keycloak/realms/ol-local-realm.json
Labels: Needs Review

#2664 Deactivate audit enrollment before deferral
  courses/api.py
  courses/api_test.py
Labels: Needs Review

#2672 Update urlconf to add accessible schema/Swagger URLs, add better typing for B2B data, update OpenAPI spec
  main/urls.py
  openapi/specs/v0.yaml
  openapi/specs/v1.yaml
  openapi/specs/v2.yaml
  users/serializers.py
Labels: Needs Review

#2674 Adding docs for B2B provisioning
  README.md
  docs/source/configuration/b2b.rst
  docs/source/configuration/index.rst
  get-pants.sh
  pants
Labels: Needs Review
