Repository mitodl/mitxonline, pull requests merged in 2025-04, with the labels that each got.

#2583 A few small schema fixes (optional fields)
  cms/serializers.py
  courses/serializers/v1/courses.py
  courses/serializers/v2/courses.py
  openapi/specs/v0.yaml
Labels: Needs Review

#2585 Add xdist so tests can be run faster
  .pre-commit-config.yaml
  .secrets.baseline
  conftest.py
  ecommerce/api_test.py
  ecommerce/serializers_test.py
  ecommerce/views_test.py
  poetry.lock
  pyproject.toml
  scripts/test/python_tests.sh
Labels: Needs Review

#2584 Successfully enroll in test course runs without clalling edX
  courses/api.py
  courses/management/commands/populate_course_data.py
  courses/models.py
Labels: Needs Review

#2589 Add edx username field to OpenEdxUser
  openedx/api.py
  openedx/api_test.py
  openedx/constants.py
  openedx/migrations/0007_add_edx_username.py
  openedx/models.py
  pytest.ini
  users/factories.py
  users/models.py
  users/models_test.py
Labels: Needs Review

#2595 OpenAPI Schema Fixes
  courses/serializers/v1/base.py
  courses/serializers/v2/courses.py
  courses/serializers/v2/programs.py
  openapi/specs/v0.yaml
Labels: Needs Review

#2593 Populate edx_username from existing user records
  openedx/migrations/0008_populate_edx_username.py
Labels: Needs Review

#2597 Make Preview certificate work in the CMS
  cms/models.py
Labels: Needs Review

#2601 New user onboarding api and ui with Keycloak
  authentication/new_serializers.py
  authentication/new_serializers_test.py
  authentication/new_urls.py
  authentication/new_views.py
  authentication/new_views_test.py
  frontend/public/src/components/forms/new_ProfileFormFields.js
  frontend/public/src/components/forms/new_RegisterDetailsForm.js
  frontend/public/src/constants.js
  frontend/public/src/containers/App.js
  frontend/public/src/containers/pages/register/new_RegisterAdditionalDetailsPage.js
  frontend/public/src/containers/pages/register/new_RegisterDetailsPage.js
  frontend/public/src/lib/notificationsApi.js
  frontend/public/src/lib/queries/new_auth.js
  frontend/public/src/lib/queries/users.js
  frontend/public/src/lib/urls.js
  main/constants.py
  main/urls.py
  openapi/specs/v0.yaml
  users/new_views.py
  users/urls.py
Labels: Needs Review

#2606 Change references to wagtailcore.pagerevision to wagtailcore.revision
  .env.example
  courses/migrations/0020_courseruncertificate_certificate_page_revision.py
  courses/migrations/0021_programcertificate.py
  courses/migrations/0026_alter_courseruncertificate_certificate_page_revision.py
  courses/migrations/0027_alter_programcertificate_certificate_page_revision.py
  courses/migrations/0028_alter_certificate_models_make_page_revision_blankable.py
  micromasters_import/migrations/0003_course_certificate_id_mapping.py
  micromasters_import/migrations/0004_add_program_certificate_revision.py
Labels: Waiting on Author

#2615 Remove override of User.USERNAME
  Dockerfile
  poetry.lock
  pyproject.toml
  users/models.py
Labels: Needs Review

#2594 Switch to using edx_username
  authentication/api_test.py
  authentication/pipeline/user.py
  authentication/pipeline/user_test.py
  courses/admin.py
  courses/api.py
  courses/api_test.py
  courses/management/commands/manage_certificates.py
  courses/management/commands/manage_program_certificates.py
  courses/management/commands/test_manage_certificate.py
  courses/management/commands/test_manage_program_certificate.py
  courses/management/commands/test_unenroll_enrollment.py
  courses/management/commands/unenroll_enrollment.py
  courses/management/utils.py
  courses/models.py
  courses/models_test.py
  courses/serializers/v1/programs.py
  courses/serializers/v1/programs_test.py
  ecommerce/api.py
  ecommerce/management/commands/generate_legacy_enrollment_codes.py
  ecommerce/management/commands/refund_fulfilled_order.py
  ecommerce/views_test.py
  flexiblepricing/models.py
  hubspot_sync/task_helpers.py
  hubspot_sync/task_helpers_test.py
  main/templates/hijack/notification.html
  main/templates/mail/support/body.html
  openedx/api.py
  openedx/api_test.py
  openedx/exceptions.py
  openedx/factories.py
  openedx/management/commands/regenerate_edx_auth_tokens.py
  openedx/management/commands/repair_missing_courseware_records.py
  openedx/management/commands/retry_edx_enrollment.py
  openedx/management/commands/sync_enrollments.py
  openedx/management/commands/update_edx_profiles.py
  pytest.ini
  users/admin.py
  users/factories.py
  users/management/commands/create_user.py
  users/management/commands/find_username_conflicts.py
  users/management/commands/retire_users.py
  users/management/tests/find_username_conflicts_test.py
  users/management/tests/retire_users_test.py
  users/management/tests/unblock_users_test.py
  users/models.py
  users/models_test.py
  users/serializers.py
  users/serializers_test.py
  users/utils.py
  users/utils_test.py
  users/views_test.py
Labels: Waiting on Author

#2604 dockerfile enhancements
  Dockerfile
  apt.txt
  docker-compose.yml
Labels: enhancement, DevOps, Needs Review

#2622 Fix some issues with Docker infra config
  Dockerfile
  docker-compose.yml
Labels: Needs Review
